package net.blueskiez77.lord_of_the_rings__middle_earth.common.block;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.function.BiFunction;
import java.util.function.Function;
import java.util.function.UnaryOperator;
import net.blueskiez77.lord_of_the_rings__middle_earth.LOTRMod;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.LOTREntityTags;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.item.LOTRAnimalJarItem;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.recipe.LOTRCraftingTable;
import net.minecraft.core.Registry;
import net.minecraft.core.particles.ParticleTypes;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.util.ColorRGBA;
import net.minecraft.util.valueproviders.UniformInt;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.PlaceOnWaterBlockItem;
import net.minecraft.world.item.StandingAndWallBlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.item.component.ItemLore;
import net.minecraft.network.chat.Component;
import net.minecraft.core.component.DataComponents;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.item.LOTRTreasurePileItem;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.item.LOTRItems;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.item.LOTRFoodItems;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.LOTRSounds;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.item.LOTRBarrelItem;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.item.LOTRPlateItem;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.item.LOTRVessel;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.entity.EntityTypes;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.WebBlock;
import net.minecraft.world.level.block.ButtonBlock;
import net.minecraft.world.level.block.CarpetBlock;
import net.minecraft.world.level.block.ColoredFallingBlock;
import net.minecraft.world.level.block.CropBlock;
import net.minecraft.world.level.block.DirtPathBlock;
import net.minecraft.world.level.block.DropExperienceBlock;
import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.FenceBlock;
import net.minecraft.world.level.block.FenceGateBlock;
import net.minecraft.world.level.block.IronBarsBlock;
import net.minecraft.world.level.block.LadderBlock;
import net.minecraft.world.level.block.PressurePlateBlock;
import net.minecraft.world.level.block.RotatedPillarBlock;
import net.minecraft.world.level.block.SlabBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.StairBlock;
import net.minecraft.world.level.block.TorchBlock;
import net.minecraft.world.level.block.TransparentBlock;
import net.minecraft.world.level.block.TrapDoorBlock;
import net.minecraft.world.level.block.UntintedParticleLeavesBlock;
import net.minecraft.world.level.block.VineBlock;
import net.minecraft.world.level.block.WallBlock;
import net.minecraft.world.level.block.WallTorchBlock;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.DoubleBlockHalf;
import net.minecraft.world.level.block.state.properties.BlockStateProperties;
import net.minecraft.world.level.block.state.properties.NoteBlockInstrument;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;
import net.minecraft.world.phys.shapes.VoxelShape;
import net.blueskiez77.lord_of_the_rings__middle_earth.common.item.LOTRKebabStandItem;

import static net.blueskiez77.lord_of_the_rings__middle_earth.common.block.LOTRBlocks.*;
import static net.blueskiez77.lord_of_the_rings__middle_earth.common.block.LOTRUtilityBlocks.*;
import static net.blueskiez77.lord_of_the_rings__middle_earth.common.block.LOTRDecorationBlocks.*;
import static net.blueskiez77.lord_of_the_rings__middle_earth.common.block.LOTRFoodBlocks.*;
import static net.blueskiez77.lord_of_the_rings__middle_earth.common.block.LOTRMiscBlocks.*;
import static net.blueskiez77.lord_of_the_rings__middle_earth.common.block.LOTRCombatBlocks.*;

/**
 * The LOTR blocks of tabBlock ("Middle-earth Blocks"): stone, bricks, ores and storage blocks, wood, and their stairs, slabs, walls and pillars.
 * Split out of LOTRBlocks by creative tab; LOTRBlocks keeps the shared
 * builders and family lists and loads this class from its init.
 */
public final class LOTRBuildingBlocks {

    public static final Block TIN_ORE = registerCube("tin_ore", 3.0f, 3.0f, Tier.STONE);
    public static final Block SILVER_ORE = registerCube("silver_ore", 3.0f, 3.0f, Tier.IRON);
    public static final Block MITHRIL_ORE = registerCube("mithril_ore", 4.0f, 6.0f, Tier.IRON);
    public static final Block SALT_ORE = registerCube("salt_ore", 3.0f, 3.0f, Tier.NONE);
    public static final Block SALTPETER_ORE = registerOre("saltpeter_ore", Tier.NONE, 0, 0, 2);
    public static final Block SULFUR_ORE = registerOre("sulfur_ore", Tier.NONE, 0, 0, 2);

    public static final Block AMBER_BLOCK = registerCube("amber_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block AMBER_ORE = registerOre("amber_ore", Tier.IRON, 0, 0, 2);
    public static final Block ANGMAR_BRICK = registerCube("angmar_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_ANGMAR_BRICK = registerCube("cracked_angmar_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block ANGMAR_SNOW_BRICK = registerCube("angmar_snow_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block ARNOR_BRICK = registerCube("arnor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_ARNOR_BRICK = registerCube("carved_arnor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_ARNOR_BRICK = registerCube("cracked_arnor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MOSSY_ARNOR_BRICK = registerCube("mossy_arnor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block NUMENOREAN_BRICK = registerCube("numenorean_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_NUMENOREAN_BRICK = registerCube("carved_numenorean_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_BLACK_UMBAR_BRICK = registerCube("carved_black_umbar_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block BLACK_URUK_STEEL_BLOCK = registerCube("black_uruk_steel_block", 5.0f, 6.0f, Tier.STONE, SoundType.METAL);
    public static final Block BLUE_CARVED_BRICK = registerCube("blue_carved_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block BLUE_DWARF_STEEL_BLOCK = registerCube("blue_dwarf_steel_block", 5.0f, 6.0f, Tier.STONE, SoundType.METAL);
    public static final Block BLUE_ROCK = registerCube("blue_rock", 1.5f, 6.0f, Tier.NONE);
    public static final Block BLUE_ROCK_BRICK = registerCube("blue_rock_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block BRONZE_BLOCK = registerCube("bronze_block", 5.0f, 6.0f, Tier.STONE, SoundType.METAL);
    public static final Block CHALK = registerCube("chalk", 1.5f, 6.0f, Tier.NONE);
    public static final Block CHALK_BRICK = registerCube("chalk_brick", 1.5f, 6.0f, Tier.NONE);
    // LOTRBlockClayTile: hardness 1.25, setResistance(7) -- 4.2 in modern units.
    public static final Block CLAY_TILE = registerCube("clay_tile", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_BLACK = registerCube("clay_tile_dyed_black", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_BLUE = registerCube("clay_tile_dyed_blue", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_BROWN = registerCube("clay_tile_dyed_brown", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_CYAN = registerCube("clay_tile_dyed_cyan", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_GRAY = registerCube("clay_tile_dyed_gray", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_GREEN = registerCube("clay_tile_dyed_green", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_LIGHT_BLUE = registerCube("clay_tile_dyed_light_blue", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_LIME = registerCube("clay_tile_dyed_lime", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_MAGENTA = registerCube("clay_tile_dyed_magenta", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_ORANGE = registerCube("clay_tile_dyed_orange", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_PINK = registerCube("clay_tile_dyed_pink", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_PURPLE = registerCube("clay_tile_dyed_purple", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_RED = registerCube("clay_tile_dyed_red", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_SILVER = registerCube("clay_tile_dyed_silver", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_WHITE = registerCube("clay_tile_dyed_white", 1.25f, 4.2f, Tier.NONE);
    public static final Block CLAY_TILE_DYED_YELLOW = registerCube("clay_tile_dyed_yellow", 1.25f, 4.2f, Tier.NONE);
    public static final Block DALE_BRICK = registerCube("dale_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DALE_CARVED_BRICK = registerCube("dale_carved_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DALE_CRACKED_BRICK = registerCube("dale_cracked_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DALE_MOSSY_BRICK = registerCube("dale_mossy_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DOL_AMROTH_BRICK = registerCube("dol_amroth_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DOL_GULDUR_BRICK = registerCube("dol_guldur_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_DOL_GULDUR_BRICK = registerCube("carved_dol_guldur_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_DOL_GULDUR_BRICK = registerCube("cracked_dol_guldur_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MOSSY_DOL_GULDUR_BRICK = registerCube("mossy_dol_guldur_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DORWINION_BRICK = registerCube("dorwinion_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_DORWINION_BRICK = registerCube("carved_dorwinion_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_DORWINION_BRICK = registerCube("cracked_dorwinion_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DORWINION_FLOWERS_BRICK = registerCube("dorwinion_flowers_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MOSSY_DORWINION_BRICK = registerCube("mossy_dorwinion_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DWARF_STEEL_BLOCK = registerCube("dwarf_steel_block", 5.0f, 6.0f, Tier.STONE, SoundType.METAL);
    public static final Block DWARVEN_BRICK = registerCube("dwarven_brick", 1.5f, 6.0f, Tier.NONE);

    public static final Block DWARVEN_SILVER_BRICK = registerCube("dwarven_silver_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DWARVEN_GOLD_BRICK = registerCube("dwarven_gold_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block DWARVEN_MITHRIL_BRICK = registerCube("dwarven_mithril_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_DWARVEN_BRICK = registerCube("carved_dwarven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_DWARVEN_BRICK = registerCube("cracked_dwarven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block GLOWING_DWARVEN_BRICK = registerCube("glowing_dwarven_brick", 1.5f, 6.0f, Tier.NONE, SoundType.STONE, 15);
    public static final Block OBSIDIAN_DWARVEN_BRICK = registerCube("obsidian_dwarven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block ELF_STEEL_BLOCK = registerCube("elf_steel_block", 5.0f, 6.0f, Tier.NONE, SoundType.METAL);
    public static final Block GALADHRIM_BRICK = registerCube("galadhrim_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_GALADHRIM_BRICK = registerCube("carved_galadhrim_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_GALADHRIM_BRICK = registerCube("cracked_galadhrim_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block GALADHRIM_GOLD_BRICK = registerCube("galadhrim_gold_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MOSSY_GALADHRIM_BRICK = registerCube("mossy_galadhrim_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block GALADHRIM_SILVER_BRICK = registerCube("galadhrim_silver_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block GALVORN_BLOCK = registerCube("galvorn_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block GILDED_IRON_BLOCK = registerCube("gilded_iron_block", 5.0f, 6.0f, Tier.NONE, SoundType.METAL);
    public static final Block GLOWSTONE_ORE = registerOre("glowstone_ore", Tier.STONE, 11, 2, 4);
    public static final Block GONDOR_BRICK = registerCube("gondor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_GONDOR_BRICK = registerCube("carved_gondor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_BLACK_GONDOR_BRICK = registerCube("carved_black_gondor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_GONDOR_BRICK = registerCube("cracked_gondor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MOSSY_GONDOR_BRICK = registerCube("mossy_gondor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block GONDOR_ROCK = registerCube("gondor_rock", 1.5f, 6.0f, Tier.NONE);
    public static final Block GONDOR_COBBLEBRICK = registerCube("gondor_cobblebrick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_GONDOR_COBBLEBRICK = registerCube("cracked_gondor_cobblebrick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MOSSY_GONDOR_COBBLEBRICK = registerCube("mossy_gondor_cobblebrick", 1.5f, 6.0f, Tier.NONE);
    public static final Block GULDURIL_BLOCK = registerCube("gulduril_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL, 11);

    public static final Block GULDURIL_MORDOR_ORE = registerOre("gulduril_mordor_ore", Tier.IRON, 11, 2, 5);
    public static final Block GULDURIL_ORE = registerOre("gulduril_ore", Tier.IRON, 11, 2, 5);
    public static final Block HIGH_ELVEN_BRICK = registerCube("high_elven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_HIGH_ELVEN_BRICK = registerCube("carved_high_elven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_HIGH_ELVEN_BRICK = registerCube("cracked_high_elven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block HIGH_ELVEN_GOLD_BRICK = registerCube("high_elven_gold_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MOSSY_HIGH_ELVEN_BRICK = registerCube("mossy_high_elven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block HIGH_ELVEN_SILVER_BRICK = registerCube("high_elven_silver_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MITHRIL_BLOCK = registerCube("mithril_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block MORDOR_BRICK = registerCube("mordor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_MORDOR_BRICK = registerCube("carved_mordor_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_MORDOR_BRICK = registerCube("cracked_mordor_brick", 1.5f, 6.0f, Tier.NONE);
    // Gulduril bricks have no textures of their own: LOTRBlockGuldurilBrick was
    // a base brick with a glowing crystal overlay, so each borrows the brick it
    // was cut from via TEXTURE_SOURCE. Light 0.75 -> 11, hardness 3.0,
    // resistance 10.0 legacy -> 6.0 modern.
    public static final Block GULDURIL_MORDOR_BRICK = registerGulduril("gulduril_mordor_brick");
    public static final Block GULDURIL_CRACKED_MORDOR_BRICK = registerGulduril("gulduril_cracked_mordor_brick");
    public static final Block GULDURIL_ANGMAR_BRICK = registerGulduril("gulduril_angmar_brick");
    public static final Block GULDURIL_CRACKED_ANGMAR_BRICK = registerGulduril("gulduril_cracked_angmar_brick");
    public static final Block GULDURIL_DOL_GULDUR_BRICK = registerGulduril("gulduril_dol_guldur_brick");
    public static final Block GULDURIL_CRACKED_DOL_GULDUR_BRICK = registerGulduril("gulduril_cracked_dol_guldur_brick");
    public static final Block GULDURIL_GONDOR_BRICK = registerGulduril("gulduril_gondor_brick");
    public static final Block GULDURIL_MOSSY_GONDOR_BRICK = registerGulduril("gulduril_mossy_gondor_brick");
    public static final Block GULDURIL_CRACKED_GONDOR_BRICK = registerGulduril("gulduril_cracked_gondor_brick");
    public static final Block GULDURIL_NUMENOREAN_BRICK = registerGulduril("gulduril_numenorean_brick");
    public static final Block MORDOR_DIRT = registerSoil("mordor_dirt", 0.5f, 0.5f, SoundType.GRAVEL);
    public static final Block MORDOR_GRAVEL = registerFalling("mordor_gravel", 0.6f, 0xFF3A3A3A);
    public static final Block MORDOR_MOSS_ROCK = registerCube("mordor_moss_rock", 1.5f, 6.0f, Tier.NONE);
    public static final Block MORDOR_ROCK = registerCubeColumn("mordor_rock", 1.5f, 6.0f, Tier.NONE);
    public static final Block MORWAITH_BRICK = registerCube("morwaith_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MORGUL_IRON_MORDOR_ORE = registerCube("morgul_iron_mordor_ore", 3.0f, 3.0f, Tier.STONE);
    public static final Block MORGUL_IRON_ORE = registerCube("morgul_iron_ore", 3.0f, 3.0f, Tier.STONE);
    public static final Block MORGUL_STEEL_BLOCK = registerCubeColumn("morgul_steel_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block CRACKED_MORWAITH_BRICK = registerCube("cracked_morwaith_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block NAURITE_BLOCK = registerCube("naurite_block", 5.0f, 6.0f, Tier.NONE, SoundType.METAL, 7);
    public static final Block NAURITE_ORE = registerOre("naurite_ore", Tier.NONE, 7, 0, 2);
    public static final Block NEAR_HARAD_BRICK = registerCube("near_harad_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block NEAR_HARAD_CARVED_BRICK = registerCube("near_harad_carved_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block NEAR_HARAD_CRACKED_BRICK = registerCube("near_harad_cracked_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block NEAR_HARAD_LAPIS_BRICK = registerCube("near_harad_lapis_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block NEAR_HARAD_RED_BRICK = registerCube("near_harad_red_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block NEAR_HARAD_RED_CARVED_BRICK = registerCube("near_harad_red_carved_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block NEAR_HARAD_RED_CRACKED_BRICK = registerCube("near_harad_red_cracked_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block OBSIDIAN_GRAVEL = registerFalling("obsidian_gravel", 0.6f, 0xFF1B1B22);
    public static final Block OPAL_BLOCK = registerCube("opal_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block OPAL_ORE = registerOre("opal_ore", Tier.IRON, 0, 0, 2);
    public static final Block ORC_PLATING_IRON = registerCube("orc_plating_iron", 3.0f, 6.0f, Tier.NONE, SoundType.METAL);
    public static final Block ORC_PLATING_RUST = registerCube("orc_plating_rust", 3.0f, 6.0f, Tier.NONE, SoundType.METAL);
    public static final Block ORC_STEEL_BLOCK = registerCubeColumn("orc_steel_block", 5.0f, 6.0f, Tier.STONE, SoundType.METAL);
    public static final Block PEARL_BLOCK = registerCube("pearl_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);

    public static final Block QUAGMIRE = track(ALL_CUBES, track(SHOVEL_MINEABLE, register("quagmire",
            LOTRQuagmireBlock::new,
            BlockBehaviour.Properties.of()
                    .mapColor(MapColor.DIRT)
                    // LOTRMod: quagmire.setHardness(1.0f).setStepSound(soundTypeGravel).
                    .strength(1.0f)
                    .sound(SoundType.GRAVEL)
                    .noCollision()
                    .noOcclusion(),
            true)));
    public static final Block QUENDITE_BLOCK = registerCube("quendite_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL, 11);
    public static final Block QUENDITE_ORE = registerOre("quendite_ore", Tier.IRON, 11, 2, 5);
    public static final Block RED_BRICK_CRACKED = registerCube("red_brick_cracked", 2.0f, 6.0f, Tier.NONE);
    public static final Block RED_BRICK_MOSSY = registerCube("red_brick_mossy", 2.0f, 6.0f, Tier.NONE);
    public static final Block RED_CARVED_BRICK = registerCube("red_carved_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RED_CLAY = registerSoil("red_clay", 0.6f, 0.6f, SoundType.GRAVEL);
    public static final Block RED_ROCK = registerCube("red_rock", 1.5f, 6.0f, Tier.NONE);
    public static final Block RED_ROCK_BRICK = registerCube("red_rock_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RHUN_BRICK = registerCube("rhun_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RHUN_CARVED_BRICK = registerCube("rhun_carved_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RHUN_CRACKED_BRICK = registerCube("rhun_cracked_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RHUN_FLOWERS_BRICK = registerCube("rhun_flowers_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RHUN_GOLD_BRICK = registerCube("rhun_gold_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RHUN_MOSSY_BRICK = registerCube("rhun_mossy_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RHUN_RED_BRICK = registerCube("rhun_red_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block RHUN_RED_CARVED_BRICK = registerCube("rhun_red_carved_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block ROHAN_BRICK = registerCubeColumn("rohan_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_ROHAN_BRICK = registerCube("carved_rohan_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block ROHAN_ROCK = registerCube("rohan_rock", 1.5f, 6.0f, Tier.NONE);
    public static final Block RUBY_BLOCK = registerCube("ruby_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block RUBY_ORE = registerOre("ruby_ore", Tier.IRON, 0, 0, 2);
    public static final Block SALT_BLOCK = registerCube("salt_block", 5.0f, 6.0f, Tier.NONE, SoundType.METAL);
    public static final Block SULFUR_BLOCK = registerCube("sulfur_block", 5.0f, 6.0f, Tier.NONE, SoundType.METAL);
    public static final Block SALTPETER_BLOCK = registerCube("saltpeter_block", 5.0f, 6.0f, Tier.NONE, SoundType.METAL);
    public static final Block SAPPHIRE_BLOCK = registerCube("sapphire_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block SAPPHIRE_ORE = registerOre("sapphire_ore", Tier.IRON, 0, 0, 2);
    public static final Block SCORCHED_STONE = registerCube("scorched_stone", 2.0f, 6.0f, Tier.NONE);
    // utumnoPillar 0/1/2. Column-textured like every other pillar.
    public static final Block FIRE_UTUMNO_PILLAR = registerPillar("fire_utumno_pillar", UTUMNO_RESISTANCE);
    public static final Block ICE_UTUMNO_PILLAR = registerPillar("ice_utumno_pillar", UTUMNO_RESISTANCE);
    public static final Block OBSIDIAN_UTUMNO_PILLAR = registerPillar("obsidian_utumno_pillar", UTUMNO_RESISTANCE);
    public static final Block SILVER_BLOCK = registerCube("silver_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block TAUREDAIN_BRICK = registerCube("tauredain_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block TAUREDAIN_CRACKED_BRICK = registerCube("tauredain_cracked_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block TAUREDAIN_GOLD_BRICK = registerCube("tauredain_gold_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block TAUREDAIN_MOSSY_BRICK = registerCube("tauredain_mossy_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block TAUREDAIN_OBSIDIAN_BRICK = registerCube("tauredain_obsidian_brick", 1.5f, 6.0f, Tier.NONE);

    public static final Block TIN_BLOCK = registerCube("tin_block", 5.0f, 6.0f, Tier.STONE, SoundType.METAL);
    public static final Block UMBAR_BRICK = registerCube("umbar_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_UMBAR_BRICK = registerCube("carved_umbar_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_UMBAR_BRICK = registerCube("cracked_umbar_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block URUK_BRICK = registerCube("uruk_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block URUK_STEEL_BLOCK = registerCubeColumn("uruk_steel_block", 5.0f, 6.0f, Tier.STONE, SoundType.METAL);
    // LOTRBlockUtumnoBrick and LOTRBlockUtumnoPillar: setHardness(1.5) then
    // setResistance(Float.MAX_VALUE), so no explosion breaks them. Their
    // slabs, stairs and walls copy this, as the originals' did.
    public static final Block FIRE_UTUMNO_BRICK = registerCube("fire_utumno_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE);
    public static final Block UTUMNO_FIRE_TILE_BRICK = registerCube("utumno_fire_tile_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE);
    public static final Block ICE_UTUMNO_BRICK = registerCube("ice_utumno_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE);
    public static final Block GLOWING_ICE_UTUMNO_BRICK = registerCube("glowing_ice_utumno_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE, SoundType.STONE, 12);
    public static final Block UTUMNO_ICE_TILE_BRICK = registerCube("utumno_ice_tile_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE);
    public static final Block OBSIDIAN_UTUMNO_BRICK = registerCube("obsidian_utumno_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE);
    public static final Block UTUMNO_OBSIDIAN_FIRE_BRICK = registerCube("utumno_obsidian_fire_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE, SoundType.STONE, 12);
    public static final Block UTUMNO_OBSIDIAN_TILE_BRICK = registerCube("utumno_obsidian_tile_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE);
    public static final Block UTUMNO_FIRE_TILE_BRICK_WALL = registerWall("utumno_fire_tile_brick_wall", UTUMNO_FIRE_TILE_BRICK);
    public static final Block UTUMNO_ICE_TILE_BRICK_WALL = registerWall("utumno_ice_tile_brick_wall", UTUMNO_ICE_TILE_BRICK);
    public static final Block UTUMNO_OBSIDIAN_TILE_BRICK_WALL = registerWall("utumno_obsidian_tile_brick_wall", UTUMNO_OBSIDIAN_TILE_BRICK);
    public static final Block UTUMNO_FIRE_TILE_BRICK_SLAB = registerSlab("utumno_fire_tile_brick_slab", UTUMNO_FIRE_TILE_BRICK);
    public static final Block UTUMNO_ICE_TILE_BRICK_SLAB = registerSlab("utumno_ice_tile_brick_slab", UTUMNO_ICE_TILE_BRICK);
    public static final Block UTUMNO_OBSIDIAN_TILE_BRICK_SLAB = registerSlab("utumno_obsidian_tile_brick_slab", UTUMNO_OBSIDIAN_TILE_BRICK);
    public static final Block WHITE_SAND = registerFalling("white_sand", 0.6f, 0xFFE6E0CF);
    public static final Block WHITE_SANDSTONE = registerBottomTop("white_sandstone", 0.8f, 0.8f);
    public static final Block WOOD_ELVEN_BRICK = registerCube("wood_elven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CARVED_WOOD_ELVEN_BRICK = registerCube("carved_wood_elven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block CRACKED_WOOD_ELVEN_BRICK = registerCube("cracked_wood_elven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block WOOD_ELVEN_GOLD_BRICK = registerCube("wood_elven_gold_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block MOSSY_WOOD_ELVEN_BRICK = registerCube("mossy_wood_elven_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block WOOD_ELVEN_SILVER_BRICK = registerCube("wood_elven_silver_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block REMAINS = track(SHOVEL_MINEABLE, registerSoftBlock("remains", 3.0f, SoundType.GRAVEL));
    public static final Block THATCH_REED = registerSoftBlock("thatch_reed", 0.5f, SoundType.GRASS);
    public static final Block THATCH_THATCH = registerSoftBlock("thatch_thatch", 0.5f, SoundType.GRASS);

    public static final Block DIAMOND_BLOCK = registerCube("diamond_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block AMETHYST_ORE = registerOre("amethyst_ore", Tier.IRON, 0, 0, 2);
    public static final Block DIAMOND_ORE = registerOre("diamond_ore", Tier.IRON, 0, 0, 2);
    public static final Block EMERALD_ORE = registerOre("emerald_ore", Tier.IRON, 0, 0, 2);
    public static final Block MUD = track(SHOVEL_MINEABLE, registerSoftBlock("mud", 0.5f, SoundType.GRAVEL));
    // mud.1 and dirtPath.1 -- the jungle variants.
    public static final Block BARREN_JUNGLE_MUD = track(SHOVEL_MINEABLE, registerSoftBlock("barren_jungle_mud", 0.5f, SoundType.GRAVEL));
    public static final Block MUD_BRICK = registerCube("mud_brick", 1.5f, 6.0f, Tier.NONE);
    public static final Block TOPAZ_BLOCK = registerCube("topaz_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block AMETHYST_BLOCK = registerCube("amethyst_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block CORAL_BLOCK = registerCube("coral_block", 5.0f, 6.0f, Tier.NONE, SoundType.METAL);
    public static final Block EMERALD_BLOCK = registerCube("emerald_block", 5.0f, 6.0f, Tier.IRON, SoundType.METAL);
    public static final Block TOPAZ_ORE = registerOre("topaz_ore", Tier.IRON, 0, 0, 2);
    public static final Block BURNING_UTUMNO_BRICK = registerCube("burning_utumno_brick", 1.5f, UTUMNO_RESISTANCE, Tier.NONE, SoundType.STONE, 12);

    public static final Block SMOOTH_MORDOR_ROCK = registerColumn("smooth_mordor_rock");
    public static final Block SMOOTH_GONDOR_ROCK = registerColumn("smooth_gondor_rock");
    public static final Block SMOOTH_ROHAN_ROCK = registerColumn("smooth_rohan_rock");
    public static final Block SMOOTH_BLUE_ROCK = registerColumn("smooth_blue_rock");
    public static final Block SMOOTH_RED_ROCK = registerColumn("smooth_red_rock");
    public static final Block SMOOTH_CHALK = registerColumn("smooth_chalk");
    public static final Block DRYSTONE = registerCube("drystone", 1.5f, 6.0f, Tier.NONE);

    // faces 0/1, sideIcon otherwise). Material.ground, no harvest level set.
    public static final Block TERMITE_MOUND = registerSoilColumn("termite_mound", 0.5f, 1.8f, SoundType.STONE, false);

    public static final Block INFESTED_TERMITE_MOUND = registerSoilColumn("infested_termite_mound", 0.5f, 1.8f, SoundType.STONE, false);

    // colorMultiplier returned 0xFFFFFF, so it is deliberately NOT biome-tinted.
    public static final Block MUD_GRASS = registerSoilColumn("mud_grass", 0.6f, 0.6f, SoundType.GRASS, true);

    public static final Block QUENDITE_GRASS = registerSoilColumn("quendite_grass", 3.0f, 3.0f, SoundType.GRASS, false);

    public static final Block BONE_BLOCK = registerColumn("bone_block", 1.0f, 3.0f);

    public static final Block HEARTH = registerBottomTop("hearth", 1.0f, 4.8f);

    public static final Block DAUB = registerSoftBlock("daub", 1.0f, SoundType.GRASS);

    // LOTRBlockWaste: Material.ground, hardness 0.5, soundTypeSand; slows and
    // sinks you like soul sand -- see LOTRWasteBlock.
    public static final Block WASTE_BLOCK = track(SHOVEL_MINEABLE, track(ALL_CUBES, register("waste_block",
            LOTRWasteBlock::new,
            BlockBehaviour.Properties.of()
                    .mapColor(MapColor.DIRT)
                    .strength(0.5f)
                    .sound(SoundType.SAND)
                    .speedFactor(0.4f),
            true)));
    public static final Block DIRT_PATH_MUD = registerPath("dirt_path_mud");
    public static final Block MUD_FARMLAND = registerFarmland("mud_farmland");

    public static final Block CHERRY_PLANKS = registerPlanks("cherry_planks");
    public static final Block ALMOND_PLANKS = registerPlanks("almond_planks");
    public static final Block APPLE_PLANKS = registerPlanks("apple_planks");
    public static final Block ASPEN_PLANKS = registerPlanks("aspen_planks");
    public static final Block BANANA_PLANKS = registerPlanks("banana_planks");
    public static final Block BAOBAB_PLANKS = registerPlanks("baobab_planks");
    public static final Block BEECH_PLANKS = registerPlanks("beech_planks");
    public static final Block CEDAR_PLANKS = registerPlanks("cedar_planks");
    public static final Block CHARRED_PLANKS = registerPlanks("charred_planks");
    public static final Block CHESTNUT_PLANKS = registerPlanks("chestnut_planks");
    public static final Block CYPRESS_PLANKS = registerPlanks("cypress_planks");
    public static final Block DATE_PALM_PLANKS = registerPlanks("date_palm_planks");
    public static final Block DRAGON_PLANKS = registerPlanks("dragon_planks");
    public static final Block FIR_PLANKS = registerPlanks("fir_planks");
    public static final Block GREEN_OAK_PLANKS = registerPlanks("green_oak_planks");
    public static final Block HOLLY_PLANKS = registerPlanks("holly_planks");
    public static final Block KANUKA_PLANKS = registerPlanks("kanuka_planks");
    public static final Block LAIRELOSSE_PLANKS = registerPlanks("lairelosse_planks");
    public static final Block LARCH_PLANKS = registerPlanks("larch_planks");
    public static final Block LEBETHRON_PLANKS = registerPlanks("lebethron_planks");
    public static final Block LEMON_PLANKS = registerPlanks("lemon_planks");
    public static final Block LIME_PLANKS = registerPlanks("lime_planks");
    public static final Block MAHOGANY_PLANKS = registerPlanks("mahogany_planks");
    public static final Block MALLORN_PLANKS = registerPlanks("mallorn_planks");
    public static final Block MANGO_PLANKS = registerPlanks("mango_planks");
    public static final Block MANGROVE_PLANKS = registerPlanks("mangrove_planks");
    public static final Block MAPLE_PLANKS = registerPlanks("maple_planks");
    public static final Block MIRK_OAK_PLANKS = registerPlanks("mirk_oak_planks");
    public static final Block OLIVE_PLANKS = registerPlanks("olive_planks");
    public static final Block ORANGE_PLANKS = registerPlanks("orange_planks");
    public static final Block PALM_PLANKS = registerPlanks("palm_planks");
    public static final Block PEAR_PLANKS = registerPlanks("pear_planks");
    public static final Block PINE_PLANKS = registerPlanks("pine_planks");
    public static final Block PLUM_PLANKS = registerPlanks("plum_planks");
    public static final Block POMEGRANATE_PLANKS = registerPlanks("pomegranate_planks");
    public static final Block REDWOOD_PLANKS = registerPlanks("redwood_planks");
    public static final Block ROTTEN_PLANKS = registerPlanks("rotten_planks");
    public static final Block SHIRE_PINE_PLANKS = registerPlanks("shire_pine_planks");
    public static final Block WILLOW_PLANKS = registerPlanks("willow_planks");

    public static final Block CHERRY_LOG = registerLog("cherry_log");
    public static final Block ALMOND_LOG = registerLog("almond_log");
    public static final Block APPLE_LOG = registerLog("apple_log");
    public static final Block ASPEN_LOG = registerLog("aspen_log");
    public static final Block BANANA_LOG = registerLog("banana_log");
    public static final Block BAOBAB_LOG = registerLog("baobab_log");
    public static final Block BEECH_LOG = registerLog("beech_log");
    public static final Block CEDAR_LOG = registerLog("cedar_log");
    public static final Block CHARRED_LOG = registerLog("charred_log");
    public static final Block CHESTNUT_LOG = registerLog("chestnut_log");
    public static final Block CYPRESS_LOG = registerLog("cypress_log");
    public static final Block DATE_PALM_LOG = registerLog("date_palm_log");
    public static final Block DRAGON_LOG = registerLog("dragon_log");
    public static final Block FIR_LOG = registerLog("fir_log");
    public static final Block GREEN_OAK_LOG = registerLog("green_oak_log");
    public static final Block HOLLY_LOG = registerLog("holly_log");
    public static final Block KANUKA_LOG = registerLog("kanuka_log");
    public static final Block LAIRELOSSE_LOG = registerLog("lairelosse_log");
    public static final Block LARCH_LOG = registerLog("larch_log");
    public static final Block LEBETHRON_LOG = registerLog("lebethron_log");
    public static final Block LEMON_LOG = registerLog("lemon_log");
    public static final Block LIME_LOG = registerLog("lime_log");
    public static final Block MAHOGANY_LOG = registerLog("mahogany_log");
    public static final Block MALLORN_LOG = registerLog("mallorn_log");
    public static final Block MANGO_LOG = registerLog("mango_log");
    public static final Block MANGROVE_LOG = registerLog("mangrove_log");
    public static final Block MAPLE_LOG = registerLog("maple_log");
    public static final Block MIRK_OAK_LOG = registerLog("mirk_oak_log");
    public static final Block OLIVE_LOG = registerLog("olive_log");
    public static final Block ORANGE_LOG = registerLog("orange_log");
    public static final Block PALM_LOG = registerLog("palm_log");
    public static final Block PEAR_LOG = registerLog("pear_log");
    public static final Block PINE_LOG = registerLog("pine_log");
    public static final Block PLUM_LOG = registerLog("plum_log");
    public static final Block POMEGRANATE_LOG = registerLog("pomegranate_log");
    public static final Block REDWOOD_LOG = registerLog("redwood_log");
    public static final Block ROTTEN_LOG = registerLog("rotten_log");
    public static final Block SHIRE_PINE_LOG = registerLog("shire_pine_log");
    public static final Block WILLOW_LOG = registerLog("willow_log");

    public static final Block ACACIA_BEAM = registerBeam("acacia_beam");
    public static final Block ALMOND_BEAM = registerBeam("almond_beam");
    public static final Block APPLE_BEAM = registerBeam("apple_beam");
    public static final Block ASPEN_BEAM = registerBeam("aspen_beam");
    public static final Block BANANA_BEAM = registerBeam("banana_beam");
    public static final Block BAOBAB_BEAM = registerBeam("baobab_beam");
    public static final Block BEECH_BEAM = registerBeam("beech_beam");
    public static final Block BIRCH_BEAM = registerBeam("birch_beam");
    public static final Block CEDAR_BEAM = registerBeam("cedar_beam");
    public static final Block CHARRED_BEAM = registerBeam("charred_beam");
    public static final Block CHERRY_BEAM = registerBeam("cherry_beam");
    public static final Block CHESTNUT_BEAM = registerBeam("chestnut_beam");
    public static final Block CYPRESS_BEAM = registerBeam("cypress_beam");
    public static final Block DARK_OAK_BEAM = registerBeam("dark_oak_beam");
    public static final Block DATE_PALM_BEAM = registerBeam("date_palm_beam");
    public static final Block DRAGON_BEAM = registerBeam("dragon_beam");
    public static final Block FIR_BEAM = registerBeam("fir_beam");
    public static final Block GREEN_OAK_BEAM = registerBeam("green_oak_beam");
    public static final Block HOLLY_BEAM = registerBeam("holly_beam");
    public static final Block JUNGLE_BEAM = registerBeam("jungle_beam");
    public static final Block KANUKA_BEAM = registerBeam("kanuka_beam");
    public static final Block LAIRELOSSE_BEAM = registerBeam("lairelosse_beam");
    public static final Block LARCH_BEAM = registerBeam("larch_beam");
    public static final Block LEBETHRON_BEAM = registerBeam("lebethron_beam");
    public static final Block LEMON_BEAM = registerBeam("lemon_beam");
    public static final Block LIME_BEAM = registerBeam("lime_beam");
    public static final Block MAHOGANY_BEAM = registerBeam("mahogany_beam");
    public static final Block MALLORN_BEAM = registerBeam("mallorn_beam");
    public static final Block MANGO_BEAM = registerBeam("mango_beam");
    public static final Block MANGROVE_BEAM = registerBeam("mangrove_beam");
    public static final Block MAPLE_BEAM = registerBeam("maple_beam");
    public static final Block MIRK_OAK_BEAM = registerBeam("mirk_oak_beam");
    public static final Block OAK_BEAM = registerBeam("oak_beam");
    public static final Block OLIVE_BEAM = registerBeam("olive_beam");
    public static final Block ORANGE_BEAM = registerBeam("orange_beam");
    public static final Block PALM_BEAM = registerBeam("palm_beam");
    public static final Block PEAR_BEAM = registerBeam("pear_beam");
    public static final Block PINE_BEAM = registerBeam("pine_beam");
    public static final Block PLUM_BEAM = registerBeam("plum_beam");
    public static final Block POMEGRANATE_BEAM = registerBeam("pomegranate_beam");
    public static final Block REDWOOD_BEAM = registerBeam("redwood_beam");
    public static final Block ROHAN_BEAM = registerBeam("rohan_beam");
    public static final Block ROHAN_GOLD_BEAM = registerBeam("rohan_gold_beam");
    public static final Block ROTTEN_BEAM = registerBeam("rotten_beam");
    public static final Block SHIRE_PINE_BEAM = registerBeam("shire_pine_beam");
    public static final Block SPRUCE_BEAM = registerBeam("spruce_beam");
    public static final Block WILLOW_BEAM = registerBeam("willow_beam");

    public static final Block ANGMAR_PILLAR = registerPillar("angmar_pillar");
    public static final Block CRACKED_ARNOR_PILLAR = registerPillar("cracked_arnor_pillar");
    public static final Block ARNOR_PILLAR = registerPillar("arnor_pillar");
    public static final Block NUMENOREAN_PILLAR = registerPillar("numenorean_pillar");
    public static final Block BLUE_ROCK_PILLAR = registerPillar("blue_rock_pillar");
    public static final Block BRICK_PILLAR = registerPillar("brick_pillar");
    public static final Block CHALK_PILLAR = registerPillar("chalk_pillar");
    public static final Block DALE_PILLAR = registerPillar("dale_pillar");
    public static final Block DOL_GULDUR_PILLAR = registerPillar("dol_guldur_pillar");
    public static final Block MOSSY_DORWINION_PILLAR = registerPillar("mossy_dorwinion_pillar");
    public static final Block DORWINION_PILLAR = registerPillar("dorwinion_pillar");
    public static final Block CRACKED_DWARVEN_PILLAR = registerPillar("cracked_dwarven_pillar");
    public static final Block DWARVEN_PILLAR = registerPillar("dwarven_pillar");
    public static final Block CRACKED_GALADHRIM_PILLAR = registerPillar("cracked_galadhrim_pillar");
    public static final Block GALADHRIM_PILLAR = registerPillar("galadhrim_pillar");
    public static final Block GONDOR_PILLAR = registerPillar("gondor_pillar");
    public static final Block CRACKED_HIGH_ELVEN_PILLAR = registerPillar("cracked_high_elven_pillar");
    public static final Block HIGH_ELVEN_PILLAR = registerPillar("high_elven_pillar");
    public static final Block MORDOR_PILLAR = registerPillar("mordor_pillar");
    public static final Block NEAR_HARAD_PILLAR = registerPillar("near_harad_pillar");
    public static final Block NEAR_HARAD_RED_PILLAR = registerPillar("near_harad_red_pillar");
    public static final Block RED_ROCK_PILLAR = registerPillar("red_rock_pillar");
    public static final Block RHUN_PILLAR = registerPillar("rhun_pillar");
    public static final Block RHUN_RED_PILLAR = registerPillar("rhun_red_pillar");
    public static final Block ROHAN_PILLAR = registerPillar("rohan_pillar");
    public static final Block STONE_PILLAR = registerPillar("stone_pillar");
    public static final Block TAUR_GOLD_PILLAR = registerPillar("taur_gold_pillar");
    public static final Block TAUR_OBSIDIAN_PILLAR = registerPillar("taur_obsidian_pillar");
    public static final Block TAUREDAIN_PILLAR = registerPillar("tauredain_pillar");
    public static final Block UMBAR_PILLAR = registerPillar("umbar_pillar");
    public static final Block URUK_PILLAR = registerPillar("uruk_pillar");
    public static final Block CRACKED_WOOD_ELVEN_PILLAR = registerPillar("cracked_wood_elven_pillar");
    public static final Block WOOD_ELVEN_PILLAR = registerPillar("wood_elven_pillar");

    public static final Block BLACK_STAINED_GLASS = registerGlass("black_stained_glass");
    public static final Block BLUE_STAINED_GLASS = registerGlass("blue_stained_glass");
    public static final Block BROWN_STAINED_GLASS = registerGlass("brown_stained_glass");
    public static final Block CYAN_STAINED_GLASS = registerGlass("cyan_stained_glass");
    public static final Block GRAY_STAINED_GLASS = registerGlass("gray_stained_glass");
    public static final Block GREEN_STAINED_GLASS = registerGlass("green_stained_glass");
    public static final Block LIGHT_BLUE_STAINED_GLASS = registerGlass("light_blue_stained_glass");
    public static final Block LIME_STAINED_GLASS = registerGlass("lime_stained_glass");
    public static final Block MAGENTA_STAINED_GLASS = registerGlass("magenta_stained_glass");
    public static final Block ORANGE_STAINED_GLASS = registerGlass("orange_stained_glass");
    public static final Block PINK_STAINED_GLASS = registerGlass("pink_stained_glass");
    public static final Block PURPLE_STAINED_GLASS = registerGlass("purple_stained_glass");
    public static final Block RED_STAINED_GLASS = registerGlass("red_stained_glass");
    public static final Block SILVER_STAINED_GLASS = registerGlass("silver_stained_glass");
    public static final Block WHITE_STAINED_GLASS = registerGlass("white_stained_glass");
    public static final Block YELLOW_STAINED_GLASS = registerGlass("yellow_stained_glass");
    public static final Block GLASS = registerGlass("glass");

    public static final Block ALMOND_STAIRS = registerStairs("almond_stairs", ALMOND_PLANKS);
    public static final Block ANGMAR_BRICK_STAIRS = registerStairs("angmar_brick_stairs", ANGMAR_BRICK);
    public static final Block CRACKED_ANGMAR_BRICK_STAIRS = registerStairs("cracked_angmar_brick_stairs", CRACKED_ANGMAR_BRICK);
    public static final Block ANGMAR_SNOW_BRICK_STAIRS = registerStairs("angmar_snow_brick_stairs", ANGMAR_SNOW_BRICK);
    public static final Block APPLE_STAIRS = registerStairs("apple_stairs", APPLE_PLANKS);
    public static final Block ARNOR_BRICK_STAIRS = registerStairs("arnor_brick_stairs", ARNOR_BRICK);
    public static final Block CRACKED_ARNOR_BRICK_STAIRS = registerStairs("cracked_arnor_brick_stairs", CRACKED_ARNOR_BRICK);
    public static final Block MOSSY_ARNOR_BRICK_STAIRS = registerStairs("mossy_arnor_brick_stairs", MOSSY_ARNOR_BRICK);
    public static final Block ASPEN_STAIRS = registerStairs("aspen_stairs", ASPEN_PLANKS);
    public static final Block BANANA_STAIRS = registerStairs("banana_stairs", BANANA_PLANKS);
    public static final Block BAOBAB_STAIRS = registerStairs("baobab_stairs", BAOBAB_PLANKS);
    public static final Block BEECH_STAIRS = registerStairs("beech_stairs", BEECH_PLANKS);
    public static final Block NUMENOREAN_BRICK_STAIRS = registerStairs("numenorean_brick_stairs", NUMENOREAN_BRICK);
    public static final Block BLUE_ROCK_BRICK_STAIRS = registerStairs("blue_rock_brick_stairs", BLUE_ROCK_BRICK);
    public static final Block BLUE_ROCK_STAIRS = registerStairs("blue_rock_stairs", BLUE_ROCK);
    public static final Block CEDAR_STAIRS = registerStairs("cedar_stairs", CEDAR_PLANKS);
    public static final Block CHALK_BRICK_STAIRS = registerStairs("chalk_brick_stairs", CHALK_BRICK);
    public static final Block CHALK_STAIRS = registerStairs("chalk_stairs", CHALK);
    public static final Block CHARRED_STAIRS = registerStairs("charred_stairs", CHARRED_PLANKS);
    public static final Block CHESTNUT_STAIRS = registerStairs("chestnut_stairs", CHESTNUT_PLANKS);
    public static final Block CLAY_TILE_DYED_BLACK_STAIRS = registerStairs("clay_tile_dyed_black_stairs", CLAY_TILE_DYED_BLACK);
    public static final Block CLAY_TILE_DYED_BLUE_STAIRS = registerStairs("clay_tile_dyed_blue_stairs", CLAY_TILE_DYED_BLUE);
    public static final Block CLAY_TILE_DYED_BROWN_STAIRS = registerStairs("clay_tile_dyed_brown_stairs", CLAY_TILE_DYED_BROWN);
    public static final Block CLAY_TILE_DYED_CYAN_STAIRS = registerStairs("clay_tile_dyed_cyan_stairs", CLAY_TILE_DYED_CYAN);
    public static final Block CLAY_TILE_DYED_GRAY_STAIRS = registerStairs("clay_tile_dyed_gray_stairs", CLAY_TILE_DYED_GRAY);
    public static final Block CLAY_TILE_DYED_GREEN_STAIRS = registerStairs("clay_tile_dyed_green_stairs", CLAY_TILE_DYED_GREEN);
    public static final Block CLAY_TILE_DYED_LIGHT_BLUE_STAIRS = registerStairs("clay_tile_dyed_light_blue_stairs", CLAY_TILE_DYED_LIGHT_BLUE);
    public static final Block CLAY_TILE_DYED_LIME_STAIRS = registerStairs("clay_tile_dyed_lime_stairs", CLAY_TILE_DYED_LIME);
    public static final Block CLAY_TILE_DYED_MAGENTA_STAIRS = registerStairs("clay_tile_dyed_magenta_stairs", CLAY_TILE_DYED_MAGENTA);
    public static final Block CLAY_TILE_DYED_ORANGE_STAIRS = registerStairs("clay_tile_dyed_orange_stairs", CLAY_TILE_DYED_ORANGE);
    public static final Block CLAY_TILE_DYED_PINK_STAIRS = registerStairs("clay_tile_dyed_pink_stairs", CLAY_TILE_DYED_PINK);
    public static final Block CLAY_TILE_DYED_PURPLE_STAIRS = registerStairs("clay_tile_dyed_purple_stairs", CLAY_TILE_DYED_PURPLE);
    public static final Block CLAY_TILE_DYED_RED_STAIRS = registerStairs("clay_tile_dyed_red_stairs", CLAY_TILE_DYED_RED);
    public static final Block CLAY_TILE_DYED_WHITE_STAIRS = registerStairs("clay_tile_dyed_white_stairs", CLAY_TILE_DYED_WHITE);
    public static final Block CLAY_TILE_DYED_YELLOW_STAIRS = registerStairs("clay_tile_dyed_yellow_stairs", CLAY_TILE_DYED_YELLOW);
    public static final Block CLAY_TILE_STAIRS = registerStairs("clay_tile_stairs", CLAY_TILE);
    public static final Block CYPRESS_STAIRS = registerStairs("cypress_stairs", CYPRESS_PLANKS);
    public static final Block DALE_BRICK_STAIRS = registerStairs("dale_brick_stairs", DALE_BRICK);
    public static final Block DALE_CRACKED_BRICK_STAIRS = registerStairs("dale_cracked_brick_stairs", DALE_CRACKED_BRICK);
    public static final Block DALE_MOSSY_BRICK_STAIRS = registerStairs("dale_mossy_brick_stairs", DALE_MOSSY_BRICK);
    public static final Block DATE_PALM_STAIRS = registerStairs("date_palm_stairs", DATE_PALM_PLANKS);
    public static final Block DOL_AMROTH_BRICK_STAIRS = registerStairs("dol_amroth_brick_stairs", DOL_AMROTH_BRICK);
    public static final Block DOL_GULDUR_BRICK_STAIRS = registerStairs("dol_guldur_brick_stairs", DOL_GULDUR_BRICK);
    public static final Block CRACKED_DOL_GULDUR_BRICK_STAIRS = registerStairs("cracked_dol_guldur_brick_stairs", CRACKED_DOL_GULDUR_BRICK);
    public static final Block MOSSY_DOL_GULDUR_BRICK_STAIRS = registerStairs("mossy_dol_guldur_brick_stairs", MOSSY_DOL_GULDUR_BRICK);
    public static final Block DORWINION_BRICK_STAIRS = registerStairs("dorwinion_brick_stairs", DORWINION_BRICK);
    public static final Block CRACKED_DORWINION_BRICK_STAIRS = registerStairs("cracked_dorwinion_brick_stairs", CRACKED_DORWINION_BRICK);
    public static final Block DORWINION_FLOWERS_BRICK_STAIRS = registerStairs("dorwinion_flowers_brick_stairs", DORWINION_FLOWERS_BRICK);
    public static final Block MOSSY_DORWINION_BRICK_STAIRS = registerStairs("mossy_dorwinion_brick_stairs", MOSSY_DORWINION_BRICK);
    public static final Block DRAGON_STAIRS = registerStairs("dragon_stairs", DRAGON_PLANKS);
    public static final Block DWARVEN_BRICK_STAIRS = registerStairs("dwarven_brick_stairs", DWARVEN_BRICK);
    public static final Block CRACKED_DWARVEN_BRICK_STAIRS = registerStairs("cracked_dwarven_brick_stairs", CRACKED_DWARVEN_BRICK);
    public static final Block OBSIDIAN_DWARVEN_BRICK_STAIRS = registerStairs("obsidian_dwarven_brick_stairs", OBSIDIAN_DWARVEN_BRICK);
    public static final Block FIR_STAIRS = registerStairs("fir_stairs", FIR_PLANKS);
    public static final Block GALADHRIM_BRICK_STAIRS = registerStairs("galadhrim_brick_stairs", GALADHRIM_BRICK);
    public static final Block CRACKED_GALADHRIM_BRICK_STAIRS = registerStairs("cracked_galadhrim_brick_stairs", CRACKED_GALADHRIM_BRICK);
    public static final Block MOSSY_GALADHRIM_BRICK_STAIRS = registerStairs("mossy_galadhrim_brick_stairs", MOSSY_GALADHRIM_BRICK);
    public static final Block GONDOR_BRICK_STAIRS = registerStairs("gondor_brick_stairs", GONDOR_BRICK);
    public static final Block CRACKED_GONDOR_BRICK_STAIRS = registerStairs("cracked_gondor_brick_stairs", CRACKED_GONDOR_BRICK);
    public static final Block MOSSY_GONDOR_BRICK_STAIRS = registerStairs("mossy_gondor_brick_stairs", MOSSY_GONDOR_BRICK);
    public static final Block GONDOR_ROCK_STAIRS = registerStairs("gondor_rock_stairs", GONDOR_ROCK);
    public static final Block GONDOR_COBBLEBRICK_STAIRS = registerStairs("gondor_cobblebrick_stairs", GONDOR_COBBLEBRICK);
    public static final Block CRACKED_GONDOR_COBBLEBRICK_STAIRS = registerStairs("cracked_gondor_cobblebrick_stairs", CRACKED_GONDOR_COBBLEBRICK);
    public static final Block MOSSY_GONDOR_COBBLEBRICK_STAIRS = registerStairs("mossy_gondor_cobblebrick_stairs", MOSSY_GONDOR_COBBLEBRICK);
    public static final Block GREEN_OAK_STAIRS = registerStairs("green_oak_stairs", GREEN_OAK_PLANKS);
    public static final Block HIGH_ELVEN_BRICK_STAIRS = registerStairs("high_elven_brick_stairs", HIGH_ELVEN_BRICK);
    public static final Block CRACKED_HIGH_ELVEN_BRICK_STAIRS = registerStairs("cracked_high_elven_brick_stairs", CRACKED_HIGH_ELVEN_BRICK);
    public static final Block MOSSY_HIGH_ELVEN_BRICK_STAIRS = registerStairs("mossy_high_elven_brick_stairs", MOSSY_HIGH_ELVEN_BRICK);
    public static final Block HOLLY_STAIRS = registerStairs("holly_stairs", HOLLY_PLANKS);
    public static final Block KANUKA_STAIRS = registerStairs("kanuka_stairs", KANUKA_PLANKS);
    public static final Block LAIRELOSSE_STAIRS = registerStairs("lairelosse_stairs", LAIRELOSSE_PLANKS);
    public static final Block LARCH_STAIRS = registerStairs("larch_stairs", LARCH_PLANKS);
    public static final Block LEBETHRON_STAIRS = registerStairs("lebethron_stairs", LEBETHRON_PLANKS);
    public static final Block LEMON_STAIRS = registerStairs("lemon_stairs", LEMON_PLANKS);
    public static final Block LIME_STAIRS = registerStairs("lime_stairs", LIME_PLANKS);
    public static final Block MAHOGANY_STAIRS = registerStairs("mahogany_stairs", MAHOGANY_PLANKS);
    public static final Block MALLORN_STAIRS = registerStairs("mallorn_stairs", MALLORN_PLANKS);
    public static final Block MANGO_STAIRS = registerStairs("mango_stairs", MANGO_PLANKS);
    public static final Block MANGROVE_STAIRS = registerStairs("mangrove_stairs", MANGROVE_PLANKS);
    public static final Block MAPLE_STAIRS = registerStairs("maple_stairs", MAPLE_PLANKS);
    public static final Block MIRK_OAK_STAIRS = registerStairs("mirk_oak_stairs", MIRK_OAK_PLANKS);
    public static final Block MORDOR_BRICK_STAIRS = registerStairs("mordor_brick_stairs", MORDOR_BRICK);
    public static final Block CRACKED_MORDOR_BRICK_STAIRS = registerStairs("cracked_mordor_brick_stairs", CRACKED_MORDOR_BRICK);
    public static final Block MORDOR_ROCK_STAIRS = registerStairs("mordor_rock_stairs", MORDOR_ROCK);
    public static final Block MORWAITH_BRICK_STAIRS = registerStairs("morwaith_brick_stairs", MORWAITH_BRICK);
    public static final Block CRACKED_MORWAITH_BRICK_STAIRS = registerStairs("cracked_morwaith_brick_stairs", CRACKED_MORWAITH_BRICK);
    public static final Block MUD_BRICK_STAIRS = registerStairs("mud_brick_stairs", MUD_BRICK);
    public static final Block NEAR_HARAD_BRICK_STAIRS = registerStairs("near_harad_brick_stairs", NEAR_HARAD_BRICK);
    public static final Block NEAR_HARAD_CRACKED_BRICK_STAIRS = registerStairs("near_harad_cracked_brick_stairs", NEAR_HARAD_CRACKED_BRICK);
    public static final Block NEAR_HARAD_RED_BRICK_STAIRS = registerStairs("near_harad_red_brick_stairs", NEAR_HARAD_RED_BRICK);
    public static final Block NEAR_HARAD_RED_CRACKED_BRICK_STAIRS = registerStairs("near_harad_red_cracked_brick_stairs", NEAR_HARAD_RED_CRACKED_BRICK);
    public static final Block OLIVE_STAIRS = registerStairs("olive_stairs", OLIVE_PLANKS);
    public static final Block ORANGE_STAIRS = registerStairs("orange_stairs", ORANGE_PLANKS);
    public static final Block PALM_STAIRS = registerStairs("palm_stairs", PALM_PLANKS);
    public static final Block PEAR_STAIRS = registerStairs("pear_stairs", PEAR_PLANKS);
    public static final Block PINE_STAIRS = registerStairs("pine_stairs", PINE_PLANKS);
    public static final Block PLUM_STAIRS = registerStairs("plum_stairs", PLUM_PLANKS);
    public static final Block POMEGRANATE_STAIRS = registerStairs("pomegranate_stairs", POMEGRANATE_PLANKS);
    public static final Block RED_BRICK_CRACKED_STAIRS = registerStairs("red_brick_cracked_stairs", RED_BRICK_CRACKED);
    public static final Block RED_BRICK_MOSSY_STAIRS = registerStairs("red_brick_mossy_stairs", RED_BRICK_MOSSY);
    public static final Block RED_ROCK_BRICK_STAIRS = registerStairs("red_rock_brick_stairs", RED_ROCK_BRICK);
    public static final Block RED_ROCK_STAIRS = registerStairs("red_rock_stairs", RED_ROCK);
    public static final Block REDWOOD_STAIRS = registerStairs("redwood_stairs", REDWOOD_PLANKS);
    public static final Block RHUN_BRICK_STAIRS = registerStairs("rhun_brick_stairs", RHUN_BRICK);
    public static final Block RHUN_CRACKED_BRICK_STAIRS = registerStairs("rhun_cracked_brick_stairs", RHUN_CRACKED_BRICK);
    public static final Block RHUN_FLOWERS_BRICK_STAIRS = registerStairs("rhun_flowers_brick_stairs", RHUN_FLOWERS_BRICK);
    public static final Block RHUN_MOSSY_BRICK_STAIRS = registerStairs("rhun_mossy_brick_stairs", RHUN_MOSSY_BRICK);
    public static final Block RHUN_RED_BRICK_STAIRS = registerStairs("rhun_red_brick_stairs", RHUN_RED_BRICK);
    public static final Block ROHAN_BRICK_STAIRS = registerStairs("rohan_brick_stairs", ROHAN_BRICK);
    public static final Block ROHAN_ROCK_STAIRS = registerStairs("rohan_rock_stairs", ROHAN_ROCK);
    public static final Block ROTTEN_STAIRS = registerStairs("rotten_stairs", ROTTEN_PLANKS);
    public static final Block SCORCHED_STONE_STAIRS = registerStairs("scorched_stone_stairs", SCORCHED_STONE);
    public static final Block SHIRE_PINE_STAIRS = registerStairs("shire_pine_stairs", SHIRE_PINE_PLANKS);
    public static final Block TAUREDAIN_BRICK_STAIRS = registerStairs("tauredain_brick_stairs", TAUREDAIN_BRICK);
    public static final Block TAUREDAIN_CRACKED_BRICK_STAIRS = registerStairs("tauredain_cracked_brick_stairs", TAUREDAIN_CRACKED_BRICK);
    public static final Block TAUREDAIN_GOLD_BRICK_STAIRS = registerStairs("tauredain_gold_brick_stairs", TAUREDAIN_GOLD_BRICK);
    public static final Block TAUREDAIN_MOSSY_BRICK_STAIRS = registerStairs("tauredain_mossy_brick_stairs", TAUREDAIN_MOSSY_BRICK);
    public static final Block TAUREDAIN_OBSIDIAN_BRICK_STAIRS = registerStairs("tauredain_obsidian_brick_stairs", TAUREDAIN_OBSIDIAN_BRICK);
    public static final Block THATCH_REED_STAIRS = registerStairs("thatch_reed_stairs", THATCH_REED);
    public static final Block THATCH_THATCH_STAIRS = registerStairs("thatch_thatch_stairs", THATCH_THATCH);
    public static final Block UMBAR_BRICK_STAIRS = registerStairs("umbar_brick_stairs", UMBAR_BRICK);
    public static final Block CRACKED_UMBAR_BRICK_STAIRS = registerStairs("cracked_umbar_brick_stairs", CRACKED_UMBAR_BRICK);
    public static final Block URUK_BRICK_STAIRS = registerStairs("uruk_brick_stairs", URUK_BRICK);
    public static final Block FIRE_UTUMNO_BRICK_STAIRS = registerStairs("fire_utumno_brick_stairs", FIRE_UTUMNO_BRICK);
    public static final Block UTUMNO_FIRE_TILE_BRICK_STAIRS = registerStairs("utumno_fire_tile_brick_stairs", UTUMNO_FIRE_TILE_BRICK);
    public static final Block ICE_UTUMNO_BRICK_STAIRS = registerStairs("ice_utumno_brick_stairs", ICE_UTUMNO_BRICK);
    public static final Block UTUMNO_ICE_TILE_BRICK_STAIRS = registerStairs("utumno_ice_tile_brick_stairs", UTUMNO_ICE_TILE_BRICK);
    public static final Block OBSIDIAN_UTUMNO_BRICK_STAIRS = registerStairs("obsidian_utumno_brick_stairs", OBSIDIAN_UTUMNO_BRICK);
    public static final Block UTUMNO_OBSIDIAN_TILE_BRICK_STAIRS = registerStairs("utumno_obsidian_tile_brick_stairs", UTUMNO_OBSIDIAN_TILE_BRICK);
    public static final Block WHITE_SANDSTONE_STAIRS = registerStairs("white_sandstone_stairs", WHITE_SANDSTONE);
    public static final Block WILLOW_STAIRS = registerStairs("willow_stairs", WILLOW_PLANKS);
    public static final Block WOOD_ELVEN_BRICK_STAIRS = registerStairs("wood_elven_brick_stairs", WOOD_ELVEN_BRICK);
    public static final Block CRACKED_WOOD_ELVEN_BRICK_STAIRS = registerStairs("cracked_wood_elven_brick_stairs", CRACKED_WOOD_ELVEN_BRICK);
    public static final Block MOSSY_WOOD_ELVEN_BRICK_STAIRS = registerStairs("mossy_wood_elven_brick_stairs", MOSSY_WOOD_ELVEN_BRICK);

    public static final Block CHERRY_STAIRS = registerStairs("cherry_stairs", CHERRY_PLANKS);
    public static final Block DRYSTONE_STAIRS = registerStairs("drystone_stairs", DRYSTONE);
    public static final Block BONE_STAIRS = registerStairs("bone_stairs", BONE_BLOCK);
    public static final Block CLAY_TILE_DYED_SILVER_STAIRS = registerStairs("clay_tile_dyed_silver_stairs", CLAY_TILE_DYED_SILVER);
    public static final Block CRACKED_STONE_BRICK_STAIRS = registerStairs("cracked_stone_brick_stairs", Blocks.CRACKED_STONE_BRICKS);

    public static final Block ANGMAR_BRICK_SLAB = registerStoneSlab("angmar_brick_slab", ANGMAR_BRICK);
    public static final Block CRACKED_ANGMAR_BRICK_SLAB = registerStoneSlab("cracked_angmar_brick_slab", CRACKED_ANGMAR_BRICK);
    public static final Block ANGMAR_PILLAR_SLAB = registerStoneSlab("angmar_pillar_slab", ANGMAR_PILLAR);
    public static final Block ANGMAR_SNOW_BRICK_SLAB = registerStoneSlab("angmar_snow_brick_slab", ANGMAR_SNOW_BRICK);
    public static final Block ARNOR_BRICK_SLAB = registerStoneSlab("arnor_brick_slab", ARNOR_BRICK);
    public static final Block CRACKED_ARNOR_BRICK_SLAB = registerStoneSlab("cracked_arnor_brick_slab", CRACKED_ARNOR_BRICK);
    public static final Block CRACKED_ARNOR_PILLAR_SLAB = registerStoneSlab("cracked_arnor_pillar_slab", CRACKED_ARNOR_PILLAR);
    public static final Block MOSSY_ARNOR_BRICK_SLAB = registerStoneSlab("mossy_arnor_brick_slab", MOSSY_ARNOR_BRICK);
    public static final Block ARNOR_PILLAR_SLAB = registerStoneSlab("arnor_pillar_slab", ARNOR_PILLAR);
    public static final Block BLUE_ROCK_BRICK_SLAB = registerStoneSlab("blue_rock_brick_slab", BLUE_ROCK_BRICK);
    public static final Block BLUE_ROCK_PILLAR_SLAB = registerStoneSlab("blue_rock_pillar_slab", BLUE_ROCK_PILLAR);
    public static final Block BLUE_ROCK_SLAB = registerStoneSlab("blue_rock_slab", BLUE_ROCK);
    public static final Block BRICK_PILLAR_SLAB = registerStoneSlab("brick_pillar_slab", BRICK_PILLAR);
    public static final Block CHALK_BRICK_SLAB = registerStoneSlab("chalk_brick_slab", CHALK_BRICK);
    public static final Block CHALK_PILLAR_SLAB = registerStoneSlab("chalk_pillar_slab", CHALK_PILLAR);
    public static final Block CHALK_SLAB = registerStoneSlab("chalk_slab", CHALK);
    public static final Block CLAY_TILE_DYED_BLACK_SLAB = registerSlab("clay_tile_dyed_black_slab", CLAY_TILE_DYED_BLACK);
    public static final Block CLAY_TILE_DYED_BLUE_SLAB = registerSlab("clay_tile_dyed_blue_slab", CLAY_TILE_DYED_BLUE);
    public static final Block CLAY_TILE_DYED_BROWN_SLAB = registerSlab("clay_tile_dyed_brown_slab", CLAY_TILE_DYED_BROWN);
    public static final Block CLAY_TILE_DYED_CYAN_SLAB = registerSlab("clay_tile_dyed_cyan_slab", CLAY_TILE_DYED_CYAN);
    public static final Block CLAY_TILE_DYED_GRAY_SLAB = registerSlab("clay_tile_dyed_gray_slab", CLAY_TILE_DYED_GRAY);
    public static final Block CLAY_TILE_DYED_GREEN_SLAB = registerSlab("clay_tile_dyed_green_slab", CLAY_TILE_DYED_GREEN);
    public static final Block CLAY_TILE_DYED_LIGHT_BLUE_SLAB = registerSlab("clay_tile_dyed_light_blue_slab", CLAY_TILE_DYED_LIGHT_BLUE);
    public static final Block CLAY_TILE_DYED_LIME_SLAB = registerSlab("clay_tile_dyed_lime_slab", CLAY_TILE_DYED_LIME);
    public static final Block CLAY_TILE_DYED_MAGENTA_SLAB = registerSlab("clay_tile_dyed_magenta_slab", CLAY_TILE_DYED_MAGENTA);
    public static final Block CLAY_TILE_DYED_ORANGE_SLAB = registerSlab("clay_tile_dyed_orange_slab", CLAY_TILE_DYED_ORANGE);
    public static final Block CLAY_TILE_DYED_PINK_SLAB = registerSlab("clay_tile_dyed_pink_slab", CLAY_TILE_DYED_PINK);
    public static final Block CLAY_TILE_DYED_PURPLE_SLAB = registerSlab("clay_tile_dyed_purple_slab", CLAY_TILE_DYED_PURPLE);
    public static final Block CLAY_TILE_DYED_RED_SLAB = registerSlab("clay_tile_dyed_red_slab", CLAY_TILE_DYED_RED);
    public static final Block CLAY_TILE_DYED_WHITE_SLAB = registerSlab("clay_tile_dyed_white_slab", CLAY_TILE_DYED_WHITE);
    public static final Block CLAY_TILE_DYED_YELLOW_SLAB = registerSlab("clay_tile_dyed_yellow_slab", CLAY_TILE_DYED_YELLOW);
    public static final Block CLAY_TILE_SLAB = registerSlab("clay_tile_slab", CLAY_TILE);
    public static final Block DALE_BRICK_SLAB = registerStoneSlab("dale_brick_slab", DALE_BRICK);
    public static final Block DALE_CRACKED_BRICK_SLAB = registerStoneSlab("dale_cracked_brick_slab", DALE_CRACKED_BRICK);
    public static final Block DALE_MOSSY_BRICK_SLAB = registerStoneSlab("dale_mossy_brick_slab", DALE_MOSSY_BRICK);
    public static final Block DALE_PILLAR_SLAB = registerStoneSlab("dale_pillar_slab", DALE_PILLAR);
    public static final Block DOL_AMROTH_BRICK_SLAB = registerStoneSlab("dol_amroth_brick_slab", DOL_AMROTH_BRICK);
    public static final Block DOL_GULDUR_BRICK_SLAB = registerStoneSlab("dol_guldur_brick_slab", DOL_GULDUR_BRICK);
    public static final Block CRACKED_DOL_GULDUR_BRICK_SLAB = registerStoneSlab("cracked_dol_guldur_brick_slab", CRACKED_DOL_GULDUR_BRICK);
    public static final Block MOSSY_DOL_GULDUR_BRICK_SLAB = registerStoneSlab("mossy_dol_guldur_brick_slab", MOSSY_DOL_GULDUR_BRICK);
    public static final Block DOL_GULDUR_PILLAR_SLAB = registerStoneSlab("dol_guldur_pillar_slab", DOL_GULDUR_PILLAR);
    public static final Block DORWINION_BRICK_SLAB = registerStoneSlab("dorwinion_brick_slab", DORWINION_BRICK);
    public static final Block CRACKED_DORWINION_BRICK_SLAB = registerStoneSlab("cracked_dorwinion_brick_slab", CRACKED_DORWINION_BRICK);
    public static final Block DORWINION_FLOWERS_BRICK_SLAB = registerStoneSlab("dorwinion_flowers_brick_slab", DORWINION_FLOWERS_BRICK);
    public static final Block MOSSY_DORWINION_BRICK_SLAB = registerStoneSlab("mossy_dorwinion_brick_slab", MOSSY_DORWINION_BRICK);
    public static final Block MOSSY_DORWINION_PILLAR_SLAB = registerStoneSlab("mossy_dorwinion_pillar_slab", MOSSY_DORWINION_PILLAR);
    public static final Block DORWINION_PILLAR_SLAB = registerStoneSlab("dorwinion_pillar_slab", DORWINION_PILLAR);
    public static final Block DWARVEN_BRICK_SLAB = registerStoneSlab("dwarven_brick_slab", DWARVEN_BRICK);
    public static final Block CRACKED_DWARVEN_BRICK_SLAB = registerStoneSlab("cracked_dwarven_brick_slab", CRACKED_DWARVEN_BRICK);
    public static final Block CRACKED_DWARVEN_PILLAR_SLAB = registerStoneSlab("cracked_dwarven_pillar_slab", CRACKED_DWARVEN_PILLAR);
    public static final Block OBSIDIAN_DWARVEN_BRICK_SLAB = registerStoneSlab("obsidian_dwarven_brick_slab", OBSIDIAN_DWARVEN_BRICK);
    public static final Block DWARVEN_PILLAR_SLAB = registerStoneSlab("dwarven_pillar_slab", DWARVEN_PILLAR);
    public static final Block GALADHRIM_BRICK_SLAB = registerStoneSlab("galadhrim_brick_slab", GALADHRIM_BRICK);
    public static final Block CRACKED_GALADHRIM_BRICK_SLAB = registerStoneSlab("cracked_galadhrim_brick_slab", CRACKED_GALADHRIM_BRICK);
    public static final Block CRACKED_GALADHRIM_PILLAR_SLAB = registerStoneSlab("cracked_galadhrim_pillar_slab", CRACKED_GALADHRIM_PILLAR);
    public static final Block MOSSY_GALADHRIM_BRICK_SLAB = registerStoneSlab("mossy_galadhrim_brick_slab", MOSSY_GALADHRIM_BRICK);
    public static final Block GALADHRIM_PILLAR_SLAB = registerStoneSlab("galadhrim_pillar_slab", GALADHRIM_PILLAR);
    public static final Block GONDOR_BRICK_SLAB = registerStoneSlab("gondor_brick_slab", GONDOR_BRICK);
    public static final Block CRACKED_GONDOR_BRICK_SLAB = registerStoneSlab("cracked_gondor_brick_slab", CRACKED_GONDOR_BRICK);
    public static final Block MOSSY_GONDOR_BRICK_SLAB = registerStoneSlab("mossy_gondor_brick_slab", MOSSY_GONDOR_BRICK);
    public static final Block GONDOR_PILLAR_SLAB = registerStoneSlab("gondor_pillar_slab", GONDOR_PILLAR);
    public static final Block GONDOR_ROCK_SLAB = registerStoneSlab("gondor_rock_slab", GONDOR_ROCK);
    public static final Block HIGH_ELVEN_BRICK_SLAB = registerStoneSlab("high_elven_brick_slab", HIGH_ELVEN_BRICK);
    public static final Block CRACKED_HIGH_ELVEN_BRICK_SLAB = registerStoneSlab("cracked_high_elven_brick_slab", CRACKED_HIGH_ELVEN_BRICK);
    public static final Block CRACKED_HIGH_ELVEN_PILLAR_SLAB = registerStoneSlab("cracked_high_elven_pillar_slab", CRACKED_HIGH_ELVEN_PILLAR);
    public static final Block MOSSY_HIGH_ELVEN_BRICK_SLAB = registerStoneSlab("mossy_high_elven_brick_slab", MOSSY_HIGH_ELVEN_BRICK);
    public static final Block HIGH_ELVEN_PILLAR_SLAB = registerStoneSlab("high_elven_pillar_slab", HIGH_ELVEN_PILLAR);
    public static final Block MORDOR_BRICK_SLAB = registerStoneSlab("mordor_brick_slab", MORDOR_BRICK);
    public static final Block CRACKED_MORDOR_BRICK_SLAB = registerStoneSlab("cracked_mordor_brick_slab", CRACKED_MORDOR_BRICK);
    public static final Block MORDOR_DIRT_SLAB = registerSlab("mordor_dirt_slab", MORDOR_DIRT);
    public static final Block MORDOR_GRAVEL_SLAB = registerSlab("mordor_gravel_slab", MORDOR_GRAVEL);
    public static final Block MORDOR_PILLAR_SLAB = registerStoneSlab("mordor_pillar_slab", MORDOR_PILLAR);
    public static final Block MORDOR_ROCK_SLAB = registerStoneSlab("mordor_rock_slab", MORDOR_ROCK);
    public static final Block CRACKED_MORWAITH_BRICK_SLAB = registerStoneSlab("cracked_morwaith_brick_slab", CRACKED_MORWAITH_BRICK);
    public static final Block MUD_BRICK_SLAB = registerStoneSlab("mud_brick_slab", MUD_BRICK);
    public static final Block NEAR_HARAD_BRICK_SLAB = registerStoneSlab("near_harad_brick_slab", NEAR_HARAD_BRICK);
    public static final Block NEAR_HARAD_CRACKED_BRICK_SLAB = registerStoneSlab("near_harad_cracked_brick_slab", NEAR_HARAD_CRACKED_BRICK);
    public static final Block NEAR_HARAD_PILLAR_SLAB = registerStoneSlab("near_harad_pillar_slab", NEAR_HARAD_PILLAR);
    public static final Block NEAR_HARAD_RED_BRICK_SLAB = registerStoneSlab("near_harad_red_brick_slab", NEAR_HARAD_RED_BRICK);
    public static final Block NEAR_HARAD_RED_CRACKED_BRICK_SLAB = registerStoneSlab("near_harad_red_cracked_brick_slab", NEAR_HARAD_RED_CRACKED_BRICK);
    public static final Block NEAR_HARAD_RED_PILLAR_SLAB = registerStoneSlab("near_harad_red_pillar_slab", NEAR_HARAD_RED_PILLAR);
    public static final Block OBSIDIAN_GRAVEL_SLAB = registerSlab("obsidian_gravel_slab", OBSIDIAN_GRAVEL);
    public static final Block RED_ROCK_BRICK_SLAB = registerStoneSlab("red_rock_brick_slab", RED_ROCK_BRICK);
    public static final Block RED_ROCK_PILLAR_SLAB = registerStoneSlab("red_rock_pillar_slab", RED_ROCK_PILLAR);
    public static final Block RED_ROCK_SLAB = registerStoneSlab("red_rock_slab", RED_ROCK);
    public static final Block RHUN_BRICK_SLAB = registerStoneSlab("rhun_brick_slab", RHUN_BRICK);
    public static final Block RHUN_CRACKED_BRICK_SLAB = registerStoneSlab("rhun_cracked_brick_slab", RHUN_CRACKED_BRICK);
    public static final Block RHUN_FLOWERS_BRICK_SLAB = registerStoneSlab("rhun_flowers_brick_slab", RHUN_FLOWERS_BRICK);
    public static final Block RHUN_MOSSY_BRICK_SLAB = registerStoneSlab("rhun_mossy_brick_slab", RHUN_MOSSY_BRICK);
    public static final Block RHUN_PILLAR_SLAB = registerStoneSlab("rhun_pillar_slab", RHUN_PILLAR);
    public static final Block RHUN_RED_BRICK_SLAB = registerStoneSlab("rhun_red_brick_slab", RHUN_RED_BRICK);
    public static final Block RHUN_RED_PILLAR_SLAB = registerStoneSlab("rhun_red_pillar_slab", RHUN_RED_PILLAR);
    public static final Block ROHAN_BRICK_SLAB = registerStoneSlab("rohan_brick_slab", ROHAN_BRICK);
    public static final Block ROHAN_PILLAR_SLAB = registerStoneSlab("rohan_pillar_slab", ROHAN_PILLAR);
    public static final Block ROHAN_ROCK_SLAB = registerStoneSlab("rohan_rock_slab", ROHAN_ROCK);
    public static final Block STONE_PILLAR_SLAB = registerStoneSlab("stone_pillar_slab", STONE_PILLAR);
    public static final Block TAUREDAIN_BRICK_SLAB = registerStoneSlab("tauredain_brick_slab", TAUREDAIN_BRICK);
    public static final Block TAUREDAIN_CRACKED_BRICK_SLAB = registerStoneSlab("tauredain_cracked_brick_slab", TAUREDAIN_CRACKED_BRICK);
    public static final Block TAUREDAIN_GOLD_BRICK_SLAB = registerStoneSlab("tauredain_gold_brick_slab", TAUREDAIN_GOLD_BRICK);
    public static final Block TAUREDAIN_MOSSY_BRICK_SLAB = registerStoneSlab("tauredain_mossy_brick_slab", TAUREDAIN_MOSSY_BRICK);
    public static final Block TAUREDAIN_OBSIDIAN_BRICK_SLAB = registerStoneSlab("tauredain_obsidian_brick_slab", TAUREDAIN_OBSIDIAN_BRICK);
    public static final Block TAUREDAIN_PILLAR_SLAB = registerStoneSlab("tauredain_pillar_slab", TAUREDAIN_PILLAR);
    public static final Block THATCH_THATCH_SLAB = registerSlab("thatch_thatch_slab", THATCH_THATCH);
    public static final Block UMBAR_BRICK_SLAB = registerStoneSlab("umbar_brick_slab", UMBAR_BRICK);
    public static final Block CRACKED_UMBAR_BRICK_SLAB = registerStoneSlab("cracked_umbar_brick_slab", CRACKED_UMBAR_BRICK);
    public static final Block UMBAR_PILLAR_SLAB = registerStoneSlab("umbar_pillar_slab", UMBAR_PILLAR);
    public static final Block URUK_BRICK_SLAB = registerStoneSlab("uruk_brick_slab", URUK_BRICK);
    public static final Block URUK_PILLAR_SLAB = registerStoneSlab("uruk_pillar_slab", URUK_PILLAR);
    public static final Block FIRE_UTUMNO_BRICK_SLAB = registerSlab("fire_utumno_brick_slab", FIRE_UTUMNO_BRICK);
    public static final Block ICE_UTUMNO_BRICK_SLAB = registerSlab("ice_utumno_brick_slab", ICE_UTUMNO_BRICK);
    public static final Block OBSIDIAN_UTUMNO_BRICK_SLAB = registerSlab("obsidian_utumno_brick_slab", OBSIDIAN_UTUMNO_BRICK);
    public static final Block WHITE_SAND_SLAB = registerSlab("white_sand_slab", WHITE_SAND);
    public static final Block WHITE_SANDSTONE_SLAB = registerStoneSlab("white_sandstone_slab", WHITE_SANDSTONE);
    public static final Block WOOD_ELVEN_BRICK_SLAB = registerStoneSlab("wood_elven_brick_slab", WOOD_ELVEN_BRICK);
    public static final Block CRACKED_WOOD_ELVEN_BRICK_SLAB = registerStoneSlab("cracked_wood_elven_brick_slab", CRACKED_WOOD_ELVEN_BRICK);
    public static final Block CRACKED_WOOD_ELVEN_PILLAR_SLAB = registerStoneSlab("cracked_wood_elven_pillar_slab", CRACKED_WOOD_ELVEN_PILLAR);
    public static final Block MOSSY_WOOD_ELVEN_BRICK_SLAB = registerStoneSlab("mossy_wood_elven_brick_slab", MOSSY_WOOD_ELVEN_BRICK);
    public static final Block WOOD_ELVEN_PILLAR_SLAB = registerStoneSlab("wood_elven_pillar_slab", WOOD_ELVEN_PILLAR);

    // Cut from vanilla gravel: lotr:gravel was removed as a duplicate. */
    public static final Block GRAVEL_SLAB = registerSlab("gravel_slab", Blocks.GRAVEL);

    public static final Block SMOOTH_MORDOR_ROCK_SLAB = registerStoneSlab("smooth_mordor_rock_slab", SMOOTH_MORDOR_ROCK);

    public static final Block SMOOTH_GONDOR_ROCK_SLAB = registerStoneSlab("smooth_gondor_rock_slab", SMOOTH_GONDOR_ROCK);

    public static final Block SMOOTH_ROHAN_ROCK_SLAB = registerStoneSlab("smooth_rohan_rock_slab", SMOOTH_ROHAN_ROCK);

    public static final Block SMOOTH_BLUE_ROCK_SLAB = registerStoneSlab("smooth_blue_rock_slab", SMOOTH_BLUE_ROCK);

    public static final Block SMOOTH_RED_ROCK_SLAB = registerStoneSlab("smooth_red_rock_slab", SMOOTH_RED_ROCK);

    public static final Block SMOOTH_CHALK_SLAB = registerStoneSlab("smooth_chalk_slab", SMOOTH_CHALK);

    public static final Block DRYSTONE_SLAB = registerSlab("drystone_slab", DRYSTONE);

    public static final Block MORDOR_ROCK_WALL = registerWall("mordor_rock_wall", MORDOR_ROCK);
    public static final Block MORDOR_BRICK_WALL = registerWall("mordor_brick_wall", MORDOR_BRICK);
    public static final Block GONDOR_ROCK_WALL = registerWall("gondor_rock_wall", GONDOR_ROCK);
    public static final Block GONDOR_BRICK_WALL = registerWall("gondor_brick_wall", GONDOR_BRICK);
    public static final Block MOSSY_GONDOR_BRICK_WALL = registerWall("mossy_gondor_brick_wall", MOSSY_GONDOR_BRICK);
    public static final Block CRACKED_GONDOR_BRICK_WALL = registerWall("cracked_gondor_brick_wall", CRACKED_GONDOR_BRICK);
    public static final Block ROHAN_BRICK_WALL = registerWall("rohan_brick_wall", ROHAN_BRICK);
    public static final Block DWARVEN_BRICK_WALL = registerWall("dwarven_brick_wall", DWARVEN_BRICK);
    public static final Block ROHAN_ROCK_WALL = registerWall("rohan_rock_wall", ROHAN_ROCK);
    public static final Block CRACKED_MORDOR_BRICK_WALL = registerWall("cracked_mordor_brick_wall", CRACKED_MORDOR_BRICK);
    public static final Block GALADHRIM_BRICK_WALL = registerWall("galadhrim_brick_wall", GALADHRIM_BRICK);
    public static final Block MOSSY_GALADHRIM_BRICK_WALL = registerWall("mossy_galadhrim_brick_wall", MOSSY_GALADHRIM_BRICK);
    public static final Block CRACKED_GALADHRIM_BRICK_WALL = registerWall("cracked_galadhrim_brick_wall", CRACKED_GALADHRIM_BRICK);
    public static final Block BLUE_ROCK_WALL = registerWall("blue_rock_wall", BLUE_ROCK);
    public static final Block BLUE_ROCK_BRICK_WALL = registerWall("blue_rock_brick_wall", BLUE_ROCK_BRICK);
    public static final Block NEAR_HARAD_BRICK_WALL = registerWall("near_harad_brick_wall", NEAR_HARAD_BRICK);
    public static final Block ANGMAR_BRICK_WALL = registerWall("angmar_brick_wall", ANGMAR_BRICK);
    public static final Block CRACKED_ANGMAR_BRICK_WALL = registerWall("cracked_angmar_brick_wall", CRACKED_ANGMAR_BRICK);
    public static final Block RED_ROCK_WALL = registerWall("red_rock_wall", RED_ROCK);
    public static final Block RED_ROCK_BRICK_WALL = registerWall("red_rock_brick_wall", RED_ROCK_BRICK);
    public static final Block ARNOR_BRICK_WALL = registerWall("arnor_brick_wall", ARNOR_BRICK);
    public static final Block MOSSY_ARNOR_BRICK_WALL = registerWall("mossy_arnor_brick_wall", MOSSY_ARNOR_BRICK);
    public static final Block CRACKED_ARNOR_BRICK_WALL = registerWall("cracked_arnor_brick_wall", CRACKED_ARNOR_BRICK);
    public static final Block URUK_BRICK_WALL = registerWall("uruk_brick_wall", URUK_BRICK);
    public static final Block DOL_GULDUR_BRICK_WALL = registerWall("dol_guldur_brick_wall", DOL_GULDUR_BRICK);
    public static final Block CRACKED_DOL_GULDUR_BRICK_WALL = registerWall("cracked_dol_guldur_brick_wall", CRACKED_DOL_GULDUR_BRICK);
    public static final Block HIGH_ELVEN_BRICK_WALL = registerWall("high_elven_brick_wall", HIGH_ELVEN_BRICK);
    public static final Block MOSSY_HIGH_ELVEN_BRICK_WALL = registerWall("mossy_high_elven_brick_wall", MOSSY_HIGH_ELVEN_BRICK);
    public static final Block CRACKED_HIGH_ELVEN_BRICK_WALL = registerWall("cracked_high_elven_brick_wall", CRACKED_HIGH_ELVEN_BRICK);
    public static final Block DOL_AMROTH_BRICK_WALL = registerWall("dol_amroth_brick_wall", DOL_AMROTH_BRICK);
    public static final Block NEAR_HARAD_CRACKED_BRICK_WALL = registerWall("near_harad_cracked_brick_wall", NEAR_HARAD_CRACKED_BRICK);
    public static final Block NEAR_HARAD_RED_BRICK_WALL = registerWall("near_harad_red_brick_wall", NEAR_HARAD_RED_BRICK);
    public static final Block NEAR_HARAD_RED_CRACKED_BRICK_WALL = registerWall("near_harad_red_cracked_brick_wall", NEAR_HARAD_RED_CRACKED_BRICK);
    public static final Block CHALK_WALL = registerWall("chalk_wall", CHALK);
    public static final Block CHALK_BRICK_WALL = registerWall("chalk_brick_wall", CHALK_BRICK);
    public static final Block MUD_BRICK_WALL = registerWall("mud_brick_wall", MUD_BRICK);
    public static final Block DALE_BRICK_WALL = registerWall("dale_brick_wall", DALE_BRICK);
    public static final Block DORWINION_BRICK_WALL = registerWall("dorwinion_brick_wall", DORWINION_BRICK);
    public static final Block MOSSY_DORWINION_BRICK_WALL = registerWall("mossy_dorwinion_brick_wall", MOSSY_DORWINION_BRICK);
    public static final Block CRACKED_DORWINION_BRICK_WALL = registerWall("cracked_dorwinion_brick_wall", CRACKED_DORWINION_BRICK);
    public static final Block DORWINION_FLOWERS_BRICK_WALL = registerWall("dorwinion_flowers_brick_wall", DORWINION_FLOWERS_BRICK);
    public static final Block WHITE_SANDSTONE_WALL = registerWall("white_sandstone_wall", WHITE_SANDSTONE);
    public static final Block RHUN_BRICK_WALL = registerWall("rhun_brick_wall", RHUN_BRICK);
    public static final Block TAUREDAIN_BRICK_WALL = registerWall("tauredain_brick_wall", TAUREDAIN_BRICK);
    public static final Block TAUREDAIN_MOSSY_BRICK_WALL = registerWall("tauredain_mossy_brick_wall", TAUREDAIN_MOSSY_BRICK);
    public static final Block TAUREDAIN_CRACKED_BRICK_WALL = registerWall("tauredain_cracked_brick_wall", TAUREDAIN_CRACKED_BRICK);
    public static final Block TAUREDAIN_GOLD_BRICK_WALL = registerWall("tauredain_gold_brick_wall", TAUREDAIN_GOLD_BRICK);
    public static final Block TAUREDAIN_OBSIDIAN_BRICK_WALL = registerWall("tauredain_obsidian_brick_wall", TAUREDAIN_OBSIDIAN_BRICK);
    public static final Block CRACKED_DWARVEN_BRICK_WALL = registerWall("cracked_dwarven_brick_wall", CRACKED_DWARVEN_BRICK);
    public static final Block OBSIDIAN_DWARVEN_BRICK_WALL = registerWall("obsidian_dwarven_brick_wall", OBSIDIAN_DWARVEN_BRICK);
    public static final Block RHUN_MOSSY_BRICK_WALL = registerWall("rhun_mossy_brick_wall", RHUN_MOSSY_BRICK);
    public static final Block RHUN_CRACKED_BRICK_WALL = registerWall("rhun_cracked_brick_wall", RHUN_CRACKED_BRICK);
    public static final Block RHUN_FLOWERS_BRICK_WALL = registerWall("rhun_flowers_brick_wall", RHUN_FLOWERS_BRICK);
    public static final Block RHUN_RED_BRICK_WALL = registerWall("rhun_red_brick_wall", RHUN_RED_BRICK);
    public static final Block DALE_MOSSY_BRICK_WALL = registerWall("dale_mossy_brick_wall", DALE_MOSSY_BRICK);
    public static final Block DALE_CRACKED_BRICK_WALL = registerWall("dale_cracked_brick_wall", DALE_CRACKED_BRICK);
    public static final Block FIRE_UTUMNO_BRICK_WALL = registerWall("fire_utumno_brick_wall", FIRE_UTUMNO_BRICK);
    public static final Block ICE_UTUMNO_BRICK_WALL = registerWall("ice_utumno_brick_wall", ICE_UTUMNO_BRICK);
    public static final Block OBSIDIAN_UTUMNO_BRICK_WALL = registerWall("obsidian_utumno_brick_wall", OBSIDIAN_UTUMNO_BRICK);
    public static final Block CLAY_TILE_DYED_WHITE_WALL = registerWall("clay_tile_dyed_white_wall", CLAY_TILE_DYED_WHITE);
    public static final Block CLAY_TILE_DYED_ORANGE_WALL = registerWall("clay_tile_dyed_orange_wall", CLAY_TILE_DYED_ORANGE);
    public static final Block CLAY_TILE_DYED_MAGENTA_WALL = registerWall("clay_tile_dyed_magenta_wall", CLAY_TILE_DYED_MAGENTA);
    public static final Block CLAY_TILE_DYED_LIGHT_BLUE_WALL = registerWall("clay_tile_dyed_light_blue_wall", CLAY_TILE_DYED_LIGHT_BLUE);
    public static final Block CLAY_TILE_DYED_YELLOW_WALL = registerWall("clay_tile_dyed_yellow_wall", CLAY_TILE_DYED_YELLOW);
    public static final Block CLAY_TILE_DYED_LIME_WALL = registerWall("clay_tile_dyed_lime_wall", CLAY_TILE_DYED_LIME);
    public static final Block CLAY_TILE_DYED_PINK_WALL = registerWall("clay_tile_dyed_pink_wall", CLAY_TILE_DYED_PINK);
    public static final Block CLAY_TILE_DYED_GRAY_WALL = registerWall("clay_tile_dyed_gray_wall", CLAY_TILE_DYED_GRAY);
    public static final Block CLAY_TILE_DYED_CYAN_WALL = registerWall("clay_tile_dyed_cyan_wall", CLAY_TILE_DYED_CYAN);
    public static final Block CLAY_TILE_DYED_PURPLE_WALL = registerWall("clay_tile_dyed_purple_wall", CLAY_TILE_DYED_PURPLE);
    public static final Block CLAY_TILE_DYED_BLUE_WALL = registerWall("clay_tile_dyed_blue_wall", CLAY_TILE_DYED_BLUE);
    public static final Block CLAY_TILE_DYED_BROWN_WALL = registerWall("clay_tile_dyed_brown_wall", CLAY_TILE_DYED_BROWN);
    public static final Block CLAY_TILE_DYED_GREEN_WALL = registerWall("clay_tile_dyed_green_wall", CLAY_TILE_DYED_GREEN);
    public static final Block CLAY_TILE_DYED_RED_WALL = registerWall("clay_tile_dyed_red_wall", CLAY_TILE_DYED_RED);
    public static final Block CLAY_TILE_DYED_BLACK_WALL = registerWall("clay_tile_dyed_black_wall", CLAY_TILE_DYED_BLACK);
    public static final Block CLAY_TILE_DYED_SILVER_WALL = registerWall("clay_tile_dyed_silver_wall", CLAY_TILE_DYED_SILVER);
    public static final Block UMBAR_BRICK_WALL = registerWall("umbar_brick_wall", UMBAR_BRICK);
    public static final Block CRACKED_UMBAR_BRICK_WALL = registerWall("cracked_umbar_brick_wall", CRACKED_UMBAR_BRICK);
    public static final Block ANGMAR_SNOW_BRICK_WALL = registerWall("angmar_snow_brick_wall", ANGMAR_SNOW_BRICK);
    public static final Block MOSSY_DOL_GULDUR_BRICK_WALL = registerWall("mossy_dol_guldur_brick_wall", MOSSY_DOL_GULDUR_BRICK);
    public static final Block CRACKED_MORWAITH_BRICK_WALL = registerWall("cracked_morwaith_brick_wall", CRACKED_MORWAITH_BRICK);
    public static final Block DRYSTONE_WALL = registerWall("drystone_wall", DRYSTONE);
    public static final Block BONE_WALL = registerWall("bone_wall", BONE_BLOCK);
    public static final Block SCORCHED_STONE_WALL = registerWall("scorched_stone_wall", SCORCHED_STONE);
    public static final Block MORWAITH_BRICK_WALL = registerWall("morwaith_brick_wall", MORWAITH_BRICK);
    public static final Block NUMENOREAN_BRICK_WALL = registerWall("numenorean_brick_wall", NUMENOREAN_BRICK);
    public static final Block GONDOR_COBBLEBRICK_WALL = registerWall("gondor_cobblebrick_wall", GONDOR_COBBLEBRICK);
    public static final Block CLAY_TILE_WALL = registerWall("clay_tile_wall", CLAY_TILE);
    public static final Block RED_BRICK_MOSSY_WALL = registerWall("red_brick_mossy_wall", RED_BRICK_MOSSY);
    public static final Block RED_BRICK_CRACKED_WALL = registerWall("red_brick_cracked_wall", RED_BRICK_CRACKED);
    public static final Block WOOD_ELVEN_BRICK_WALL = registerWall("wood_elven_brick_wall", WOOD_ELVEN_BRICK);
    public static final Block MOSSY_WOOD_ELVEN_BRICK_WALL = registerWall("mossy_wood_elven_brick_wall", MOSSY_WOOD_ELVEN_BRICK);
    public static final Block CRACKED_WOOD_ELVEN_BRICK_WALL = registerWall("cracked_wood_elven_brick_wall", CRACKED_WOOD_ELVEN_BRICK);
    public static final Block MOSSY_GONDOR_COBBLEBRICK_WALL = registerWall("mossy_gondor_cobblebrick_wall", MOSSY_GONDOR_COBBLEBRICK);
    public static final Block CRACKED_GONDOR_COBBLEBRICK_WALL = registerWall("cracked_gondor_cobblebrick_wall", CRACKED_GONDOR_COBBLEBRICK);
    // Vanilla-adjacent walls it does NOT have: no plain stone wall, and no
    // cracked stone brick, mossy brick or cracked brick wall.
    public static final Block STONE_WALL = registerWall("stone_wall", Blocks.STONE);
    public static final Block CRACKED_STONE_BRICK_WALL = registerWall("cracked_stone_brick_wall", Blocks.CRACKED_STONE_BRICKS);

    public static final Block CHERRY_SLAB = registerSlab("cherry_slab", CHERRY_PLANKS);
    public static final Block ALMOND_SLAB = registerSlab("almond_slab", ALMOND_PLANKS);
    public static final Block APPLE_SLAB = registerSlab("apple_slab", APPLE_PLANKS);
    public static final Block ASPEN_SLAB = registerSlab("aspen_slab", ASPEN_PLANKS);
    public static final Block BANANA_SLAB = registerSlab("banana_slab", BANANA_PLANKS);
    public static final Block BAOBAB_SLAB = registerSlab("baobab_slab", BAOBAB_PLANKS);
    public static final Block BEECH_SLAB = registerSlab("beech_slab", BEECH_PLANKS);
    public static final Block CEDAR_SLAB = registerSlab("cedar_slab", CEDAR_PLANKS);
    public static final Block CHARRED_SLAB = registerSlab("charred_slab", CHARRED_PLANKS);
    public static final Block CHESTNUT_SLAB = registerSlab("chestnut_slab", CHESTNUT_PLANKS);
    public static final Block CYPRESS_SLAB = registerSlab("cypress_slab", CYPRESS_PLANKS);
    public static final Block DATE_PALM_SLAB = registerSlab("date_palm_slab", DATE_PALM_PLANKS);
    public static final Block DRAGON_SLAB = registerSlab("dragon_slab", DRAGON_PLANKS);
    public static final Block FIR_SLAB = registerSlab("fir_slab", FIR_PLANKS);
    public static final Block GREEN_OAK_SLAB = registerSlab("green_oak_slab", GREEN_OAK_PLANKS);
    public static final Block HOLLY_SLAB = registerSlab("holly_slab", HOLLY_PLANKS);
    public static final Block KANUKA_SLAB = registerSlab("kanuka_slab", KANUKA_PLANKS);
    public static final Block LAIRELOSSE_SLAB = registerSlab("lairelosse_slab", LAIRELOSSE_PLANKS);
    public static final Block LARCH_SLAB = registerSlab("larch_slab", LARCH_PLANKS);
    public static final Block LEBETHRON_SLAB = registerSlab("lebethron_slab", LEBETHRON_PLANKS);
    public static final Block LEMON_SLAB = registerSlab("lemon_slab", LEMON_PLANKS);
    public static final Block LIME_SLAB = registerSlab("lime_slab", LIME_PLANKS);
    public static final Block MAHOGANY_SLAB = registerSlab("mahogany_slab", MAHOGANY_PLANKS);
    public static final Block MALLORN_SLAB = registerSlab("mallorn_slab", MALLORN_PLANKS);
    public static final Block MANGO_SLAB = registerSlab("mango_slab", MANGO_PLANKS);
    public static final Block MANGROVE_SLAB = registerSlab("mangrove_slab", MANGROVE_PLANKS);
    public static final Block MAPLE_SLAB = registerSlab("maple_slab", MAPLE_PLANKS);
    public static final Block MIRK_OAK_SLAB = registerSlab("mirk_oak_slab", MIRK_OAK_PLANKS);
    public static final Block OLIVE_SLAB = registerSlab("olive_slab", OLIVE_PLANKS);
    public static final Block ORANGE_SLAB = registerSlab("orange_slab", ORANGE_PLANKS);
    public static final Block PALM_SLAB = registerSlab("palm_slab", PALM_PLANKS);
    public static final Block PEAR_SLAB = registerSlab("pear_slab", PEAR_PLANKS);
    public static final Block PINE_SLAB = registerSlab("pine_slab", PINE_PLANKS);
    public static final Block PLUM_SLAB = registerSlab("plum_slab", PLUM_PLANKS);
    public static final Block POMEGRANATE_SLAB = registerSlab("pomegranate_slab", POMEGRANATE_PLANKS);
    public static final Block REDWOOD_SLAB = registerSlab("redwood_slab", REDWOOD_PLANKS);
    public static final Block ROTTEN_SLAB = registerSlab("rotten_slab", ROTTEN_PLANKS);
    public static final Block SHIRE_PINE_SLAB = registerSlab("shire_pine_slab", SHIRE_PINE_PLANKS);
    public static final Block WILLOW_SLAB = registerSlab("willow_slab", WILLOW_PLANKS);
    public static final Block BONE_SLAB = registerSlab("bone_slab", BONE_BLOCK);
    public static final Block SCORCHED_STONE_SLAB = registerSlab("scorched_stone_slab", SCORCHED_STONE);
    public static final Block MORWAITH_BRICK_SLAB = registerStoneSlab("morwaith_brick_slab", MORWAITH_BRICK);
    public static final Block NUMENOREAN_BRICK_SLAB = registerStoneSlab("numenorean_brick_slab", NUMENOREAN_BRICK);
    public static final Block NUMENOREAN_PILLAR_SLAB = registerStoneSlab("numenorean_pillar_slab", NUMENOREAN_PILLAR);
    public static final Block GONDOR_COBBLEBRICK_SLAB = registerStoneSlab("gondor_cobblebrick_slab", GONDOR_COBBLEBRICK);
    public static final Block MOSSY_GONDOR_COBBLEBRICK_SLAB = registerStoneSlab("mossy_gondor_cobblebrick_slab", MOSSY_GONDOR_COBBLEBRICK);
    public static final Block CRACKED_GONDOR_COBBLEBRICK_SLAB = registerStoneSlab("cracked_gondor_cobblebrick_slab", CRACKED_GONDOR_COBBLEBRICK);
    public static final Block FIRE_UTUMNO_PILLAR_SLAB = registerSlab("fire_utumno_pillar_slab", FIRE_UTUMNO_PILLAR);
    public static final Block ICE_UTUMNO_PILLAR_SLAB = registerSlab("ice_utumno_pillar_slab", ICE_UTUMNO_PILLAR);
    public static final Block OBSIDIAN_UTUMNO_PILLAR_SLAB = registerSlab("obsidian_utumno_pillar_slab", OBSIDIAN_UTUMNO_PILLAR);
    public static final Block TAUR_GOLD_PILLAR_SLAB = registerStoneSlab("taur_gold_pillar_slab", TAUR_GOLD_PILLAR);
    public static final Block TAUR_OBSIDIAN_PILLAR_SLAB = registerStoneSlab("taur_obsidian_pillar_slab", TAUR_OBSIDIAN_PILLAR);
    public static final Block CLAY_TILE_DYED_SILVER_SLAB = registerSlab("clay_tile_dyed_silver_slab", CLAY_TILE_DYED_SILVER);
    public static final Block THATCH_REED_SLAB = registerSlab("thatch_reed_slab", THATCH_REED);
    public static final Block MUD_SLAB = registerSlab("mud_slab", MUD);
    public static final Block RED_BRICK_MOSSY_SLAB = registerSlab("red_brick_mossy_slab", RED_BRICK_MOSSY);
    public static final Block RED_BRICK_CRACKED_SLAB = registerSlab("red_brick_cracked_slab", RED_BRICK_CRACKED);
    public static final Block DIRT_PATH_MUD_SLAB = registerSlab("dirt_path_mud_slab", DIRT_PATH_MUD);
    public static final Block CRACKED_STONE_BRICK_SLAB = registerSlab("cracked_stone_brick_slab", Blocks.CRACKED_STONE_BRICKS);
    public static final Block SAND_SLAB = registerSlab("sand_slab", Blocks.SAND);
    public static final Block RED_SAND_SLAB = registerSlab("red_sand_slab", Blocks.RED_SAND);
    public static final Block DIRT_SLAB = registerSlab("dirt_slab", Blocks.DIRT);
    public static final Block DIRT_PATH_SLAB = registerSlab("dirt_path_slab", Blocks.DIRT_PATH);

    static {
        // mud.1 shared mud.0's single icon in the original.
        TEXTURE_SOURCE.put(BARREN_JUNGLE_MUD, MUD);
    }

    static {
        SOIL_COLUMN_TEXTURE.put(INFESTED_TERMITE_MOUND, TERMITE_MOUND);
    }

    static {
        TEXTURE_SOURCE.put(BONE_BLOCK, Blocks.BONE_BLOCK);
    }

    private LOTRBuildingBlocks() {
    }

    /** Forces class-load, so the static fields register. Called from LOTRBlocks.init. */
    static void init() {
    }
}
