package net.blueskiez77.lord_of_the_rings__middle_earth.datagen;

import java.util.concurrent.CompletableFuture;

import net.blueskiez77.lord_of_the_rings__middle_earth.common.block.LOTRBlocks;

import net.fabricmc.fabric.api.datagen.v1.FabricPackOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootSubProvider;

import net.minecraft.core.HolderLookup;

/**
 * Block loot tables. Doors use createDoorTable (one item per two-block door).
 * Glass drops itself here; use silk-touch-only tables later if you want the
 * vanilla "shatters unless silk touch" behaviour.
 */
public class LOTRBlockLootProvider extends FabricBlockLootSubProvider {

    public LOTRBlockLootProvider(FabricPackOutput output, CompletableFuture<HolderLookup.Provider> registryLookup) {
        super(output, registryLookup);
    }

    @Override
    public void generate() {
        dropSelf(LOTRBlocks.TIN_ORE);
        dropSelf(LOTRBlocks.SILVER_ORE);
        dropSelf(LOTRBlocks.MITHRIL_ORE);
        dropSelf(LOTRBlocks.SALT_ORE);
        dropSelf(LOTRBlocks.SALTPETER_ORE);
        dropSelf(LOTRBlocks.SULFUR_ORE);
        dropSelf(LOTRBlocks.AMBER_BLOCK);
        dropSelf(LOTRBlocks.AMBER_ORE);
        dropSelf(LOTRBlocks.AMETHYST_BLOCK);
        dropSelf(LOTRBlocks.AMETHYST_ORE);
        dropSelf(LOTRBlocks.ANGMAR_BRICK);
        dropSelf(LOTRBlocks.ANGMAR_CRACKED_BRICK);
        dropSelf(LOTRBlocks.ANGMAR_SNOW_BRICK);
        dropSelf(LOTRBlocks.ARNOR_BRICK);
        dropSelf(LOTRBlocks.ARNOR_CARVED_BRICK);
        dropSelf(LOTRBlocks.ARNOR_CRACKED_BRICK);
        dropSelf(LOTRBlocks.ARNOR_MOSSY_BRICK);
        dropSelf(LOTRBlocks.BLACK_GONDOR_BRICK);
        dropSelf(LOTRBlocks.BLACK_GONDOR_CARVED_BRICK);
        dropSelf(LOTRBlocks.BLACK_UMBAR_CARVED_BRICK);
        dropSelf(LOTRBlocks.BLACK_URUK_STEEL_BLOCK);
        dropSelf(LOTRBlocks.BLUE_CARVED_BRICK);
        dropSelf(LOTRBlocks.BLUE_DWARF_STEEL_BLOCK);
        dropSelf(LOTRBlocks.BLUE_ROCK);
        dropSelf(LOTRBlocks.BLUE_ROCK_BRICK);
        dropSelf(LOTRBlocks.BONE_BLOCK);
        dropSelf(LOTRBlocks.BRONZE_BLOCK);
        dropSelf(LOTRBlocks.CHALK);
        dropSelf(LOTRBlocks.CHALK_BRICK);
        dropSelf(LOTRBlocks.CLAY_TILE);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_BLACK);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_BLUE);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_BROWN);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_CYAN);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_GRAY);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_GREEN);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_LIGHT_BLUE);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_LIME);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_MAGENTA);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_ORANGE);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_PINK);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_PURPLE);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_RED);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_SILVER);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_WHITE);
        dropSelf(LOTRBlocks.CLAY_TILE_DYED_YELLOW);
        dropSelf(LOTRBlocks.CORAL_BLOCK);
        dropSelf(LOTRBlocks.DALE_BRICK);
        dropSelf(LOTRBlocks.DALE_CARVED_BRICK);
        dropSelf(LOTRBlocks.DALE_CRACKED_BRICK);
        dropSelf(LOTRBlocks.DALE_MOSSY_BRICK);
        dropSelf(LOTRBlocks.DIAMOND_BLOCK);
        dropSelf(LOTRBlocks.DIAMOND_ORE);
        dropSelf(LOTRBlocks.DOL_AMROTH_BRICK);
        dropSelf(LOTRBlocks.DOL_GULDUR_BRICK);
        dropSelf(LOTRBlocks.DOL_GULDUR_CARVED_BRICK);
        dropSelf(LOTRBlocks.DOL_GULDUR_CRACKED_BRICK);
        dropSelf(LOTRBlocks.DOL_GULDUR_MOSSY_BRICK);
        dropSelf(LOTRBlocks.DORWINION_BRICK);
        dropSelf(LOTRBlocks.DORWINION_CARVED_BRICK);
        dropSelf(LOTRBlocks.DORWINION_CRACKED_BRICK);
        dropSelf(LOTRBlocks.DORWINION_FLOWERS_BRICK);
        dropSelf(LOTRBlocks.DORWINION_MOSSY_BRICK);
        dropSelf(LOTRBlocks.DWARF_STEEL_BLOCK);
        dropSelf(LOTRBlocks.DWARVEN_BRICK);
        dropSelf(LOTRBlocks.DWARVEN_CARVED_BRICK);
        dropSelf(LOTRBlocks.DWARVEN_CRACKED_BRICK);
        dropSelf(LOTRBlocks.DWARVEN_GLOWING_BRICK);
        dropSelf(LOTRBlocks.DWARVEN_OBSIDIAN_BRICK);
        dropSelf(LOTRBlocks.ELF_STEEL_BLOCK);
        dropSelf(LOTRBlocks.EMERALD_BLOCK);
        dropSelf(LOTRBlocks.EMERALD_ORE);
        dropSelf(LOTRBlocks.GALADHRIM_BRICK);
        dropSelf(LOTRBlocks.GALADHRIM_CARVED_BRICK);
        dropSelf(LOTRBlocks.GALADHRIM_CRACKED_BRICK);
        dropSelf(LOTRBlocks.GALADHRIM_GOLD_BRICK);
        dropSelf(LOTRBlocks.GALADHRIM_MOSSY_BRICK);
        dropSelf(LOTRBlocks.GALADHRIM_SILVER_BRICK);
        dropSelf(LOTRBlocks.GALVORN_BLOCK);
        dropSelf(LOTRBlocks.GILDED_IRON_BLOCK);
        dropSelf(LOTRBlocks.GLOWSTONE_ORE);
        dropSelf(LOTRBlocks.GONDOR_BRICK);
        dropSelf(LOTRBlocks.GONDOR_CARVED_BRICK);
        dropSelf(LOTRBlocks.GONDOR_CRACKED_BRICK);
        dropSelf(LOTRBlocks.GONDOR_MOSSY_BRICK);
        dropSelf(LOTRBlocks.GONDOR_ROCK);
        dropSelf(LOTRBlocks.GONDOR_RUSTIC_BRICK);
        dropSelf(LOTRBlocks.GONDOR_RUSTIC_CRACKED_BRICK);
        dropSelf(LOTRBlocks.GONDOR_RUSTIC_MOSSY_BRICK);
        dropSelf(LOTRBlocks.GORAN_ROCK);
        dropSelf(LOTRBlocks.GRAVEL);
        dropSelf(LOTRBlocks.GULDURIL_BLOCK);
        dropSelf(LOTRBlocks.GULDURIL_MORDOR_ORE);
        dropSelf(LOTRBlocks.GULDURIL_ORE);
        dropSelf(LOTRBlocks.HIGH_ELVEN_BRICK);
        dropSelf(LOTRBlocks.HIGH_ELVEN_CARVED_BRICK);
        dropSelf(LOTRBlocks.HIGH_ELVEN_CRACKED_BRICK);
        dropSelf(LOTRBlocks.HIGH_ELVEN_GOLD_BRICK);
        dropSelf(LOTRBlocks.HIGH_ELVEN_MOSSY_BRICK);
        dropSelf(LOTRBlocks.HIGH_ELVEN_SILVER_BRICK);
        dropSelf(LOTRBlocks.MITHRIL_BLOCK);
        dropSelf(LOTRBlocks.MORDOR_BRICK);
        dropSelf(LOTRBlocks.MORDOR_CARVED_BRICK);
        dropSelf(LOTRBlocks.MORDOR_CRACKED_BRICK);
        dropSelf(LOTRBlocks.MORDOR_DIRT);
        dropSelf(LOTRBlocks.MORDOR_GRAVEL);
        dropSelf(LOTRBlocks.MORDOR_MOSS_ROCK);
        dropSelf(LOTRBlocks.MORDOR_ROCK);
        dropSelf(LOTRBlocks.MOREDAIN_BRICK);
        dropSelf(LOTRBlocks.MORGUL_IRON_MORDOR_ORE);
        dropSelf(LOTRBlocks.MORGUL_IRON_ORE);
        dropSelf(LOTRBlocks.MORGUL_STEEL_BLOCK);
        dropSelf(LOTRBlocks.MORWAITH_CRACKED_BRICK);
        dropSelf(LOTRBlocks.NAURITE_BLOCK);
        dropSelf(LOTRBlocks.NAURITE_ORE);
        dropSelf(LOTRBlocks.NEAR_HARAD_BRICK);
        dropSelf(LOTRBlocks.NEAR_HARAD_CARVED_BRICK);
        dropSelf(LOTRBlocks.NEAR_HARAD_CRACKED_BRICK);
        dropSelf(LOTRBlocks.NEAR_HARAD_LAPIS_BRICK);
        dropSelf(LOTRBlocks.NEAR_HARAD_RED_BRICK);
        dropSelf(LOTRBlocks.NEAR_HARAD_RED_CARVED_BRICK);
        dropSelf(LOTRBlocks.NEAR_HARAD_RED_CRACKED_BRICK);
        dropSelf(LOTRBlocks.OBSIDIAN_GRAVEL);
        dropSelf(LOTRBlocks.OPAL_BLOCK);
        dropSelf(LOTRBlocks.OPAL_ORE);
        dropSelf(LOTRBlocks.ORC_PLATING_IRON);
        dropSelf(LOTRBlocks.ORC_PLATING_RUST);
        dropSelf(LOTRBlocks.ORC_STEEL_BLOCK);
        dropSelf(LOTRBlocks.PEARL_BLOCK);
        dropSelf(LOTRBlocks.QUAGMIRE);
        dropSelf(LOTRBlocks.QUENDITE_BLOCK);
        dropSelf(LOTRBlocks.QUENDITE_ORE);
        dropSelf(LOTRBlocks.RED_BRICK_CRACKED);
        dropSelf(LOTRBlocks.RED_BRICK_MOSSY);
        dropSelf(LOTRBlocks.RED_CARVED_BRICK);
        dropSelf(LOTRBlocks.RED_CLAY);
        dropSelf(LOTRBlocks.RED_ROCK);
        dropSelf(LOTRBlocks.RED_ROCK_BRICK);
        dropSelf(LOTRBlocks.RED_SANDSTONE);
        dropSelf(LOTRBlocks.RHUN_BRICK);
        dropSelf(LOTRBlocks.RHUN_CARVED_BRICK);
        dropSelf(LOTRBlocks.RHUN_CRACKED_BRICK);
        dropSelf(LOTRBlocks.RHUN_FLOWERS_BRICK);
        dropSelf(LOTRBlocks.RHUN_GOLD_BRICK);
        dropSelf(LOTRBlocks.RHUN_MOSSY_BRICK);
        dropSelf(LOTRBlocks.RHUN_RED_BRICK);
        dropSelf(LOTRBlocks.RHUN_RED_CARVED_BRICK);
        dropSelf(LOTRBlocks.ROHAN_BRICK);
        dropSelf(LOTRBlocks.ROHAN_CARVED_BRICK);
        dropSelf(LOTRBlocks.ROHAN_ROCK);
        dropSelf(LOTRBlocks.RUBY_BLOCK);
        dropSelf(LOTRBlocks.RUBY_ORE);
        dropSelf(LOTRBlocks.SALT_BLOCK);
        dropSelf(LOTRBlocks.SALTPETER_BLOCK);
        dropSelf(LOTRBlocks.SAPPHIRE_BLOCK);
        dropSelf(LOTRBlocks.SAPPHIRE_ORE);
        dropSelf(LOTRBlocks.SCORCHED_STONE);
        dropSelf(LOTRBlocks.SILVER_BLOCK);
        dropSelf(LOTRBlocks.SULFUR_BLOCK);
        dropSelf(LOTRBlocks.TAUREDAIN_BRICK);
        dropSelf(LOTRBlocks.TAUREDAIN_CRACKED_BRICK);
        dropSelf(LOTRBlocks.TAUREDAIN_GOLD_BRICK);
        dropSelf(LOTRBlocks.TAUREDAIN_MOSSY_BRICK);
        dropSelf(LOTRBlocks.TAUREDAIN_OBSIDIAN_BRICK);
        dropSelf(LOTRBlocks.TIN_BLOCK);
        dropSelf(LOTRBlocks.UMBAR_BRICK);
        dropSelf(LOTRBlocks.UMBAR_CARVED_BRICK);
        dropSelf(LOTRBlocks.UMBAR_CRACKED_BRICK);
        dropSelf(LOTRBlocks.URUK_BRICK);
        dropSelf(LOTRBlocks.URUK_STEEL_BLOCK);
        dropSelf(LOTRBlocks.UTUMNO_FIRE_BRICK);
        dropSelf(LOTRBlocks.UTUMNO_FIRE_TILE_BRICK);
        dropSelf(LOTRBlocks.UTUMNO_ICE_BRICK);
        dropSelf(LOTRBlocks.UTUMNO_ICE_GLOWING_BRICK);
        dropSelf(LOTRBlocks.UTUMNO_ICE_TILE_BRICK);
        dropSelf(LOTRBlocks.UTUMNO_OBSIDIAN_BRICK);
        dropSelf(LOTRBlocks.UTUMNO_OBSIDIAN_FIRE_BRICK);
        dropSelf(LOTRBlocks.UTUMNO_OBSIDIAN_TILE_BRICK);
        dropSelf(LOTRBlocks.WHITE_SAND);
        dropSelf(LOTRBlocks.WHITE_SANDSTONE);
        dropSelf(LOTRBlocks.WOOD_ELVEN_BRICK);
        dropSelf(LOTRBlocks.WOOD_ELVEN_CARVED_BRICK);
        dropSelf(LOTRBlocks.WOOD_ELVEN_CRACKED_BRICK);
        dropSelf(LOTRBlocks.WOOD_ELVEN_GOLD_BRICK);
        dropSelf(LOTRBlocks.WOOD_ELVEN_MOSSY_BRICK);
        dropSelf(LOTRBlocks.WOOD_ELVEN_SILVER_BRICK);
        dropSelf(LOTRBlocks.ALMOND_PLANKS);
        dropSelf(LOTRBlocks.APPLE_PLANKS);
        dropSelf(LOTRBlocks.ASPEN_PLANKS);
        dropSelf(LOTRBlocks.BANANA_PLANKS);
        dropSelf(LOTRBlocks.BAOBAB_PLANKS);
        dropSelf(LOTRBlocks.BEECH_PLANKS);
        dropSelf(LOTRBlocks.CEDAR_PLANKS);
        dropSelf(LOTRBlocks.CHARRED_PLANKS);
        dropSelf(LOTRBlocks.CHERRY_PLANKS);
        dropSelf(LOTRBlocks.CHESTNUT_PLANKS);
        dropSelf(LOTRBlocks.CYPRESS_PLANKS);
        dropSelf(LOTRBlocks.DATE_PALM_PLANKS);
        dropSelf(LOTRBlocks.DRAGON_PLANKS);
        dropSelf(LOTRBlocks.FIR_PLANKS);
        dropSelf(LOTRBlocks.GREEN_OAK_PLANKS);
        dropSelf(LOTRBlocks.HOLLY_PLANKS);
        dropSelf(LOTRBlocks.KANUKA_PLANKS);
        dropSelf(LOTRBlocks.LAIRELOSSE_PLANKS);
        dropSelf(LOTRBlocks.LARCH_PLANKS);
        dropSelf(LOTRBlocks.LEBETHRON_PLANKS);
        dropSelf(LOTRBlocks.LEMON_PLANKS);
        dropSelf(LOTRBlocks.LIME_PLANKS);
        dropSelf(LOTRBlocks.MAHOGANY_PLANKS);
        dropSelf(LOTRBlocks.MALLORN_PLANKS);
        dropSelf(LOTRBlocks.MANGO_PLANKS);
        dropSelf(LOTRBlocks.MANGROVE_PLANKS);
        dropSelf(LOTRBlocks.MAPLE_PLANKS);
        dropSelf(LOTRBlocks.MIRK_OAK_PLANKS);
        dropSelf(LOTRBlocks.OLIVE_PLANKS);
        dropSelf(LOTRBlocks.ORANGE_PLANKS);
        dropSelf(LOTRBlocks.PALM_PLANKS);
        dropSelf(LOTRBlocks.PEAR_PLANKS);
        dropSelf(LOTRBlocks.PINE_PLANKS);
        dropSelf(LOTRBlocks.PLUM_PLANKS);
        dropSelf(LOTRBlocks.POMEGRANATE_PLANKS);
        dropSelf(LOTRBlocks.REDWOOD_PLANKS);
        dropSelf(LOTRBlocks.ROTTEN_PLANKS);
        dropSelf(LOTRBlocks.SHIRE_PINE_PLANKS);
        dropSelf(LOTRBlocks.WILLOW_PLANKS);
        dropSelf(LOTRBlocks.ACACIA_LEAVES);
        dropSelf(LOTRBlocks.ALMOND_LEAVES);
        dropSelf(LOTRBlocks.APPLE_LEAVES);
        dropSelf(LOTRBlocks.ASPEN_LEAVES);
        dropSelf(LOTRBlocks.BANANA_LEAVES);
        dropSelf(LOTRBlocks.BAOBAB_LEAVES);
        dropSelf(LOTRBlocks.BEECH_LEAVES);
        dropSelf(LOTRBlocks.BIRCH_LEAVES);
        dropSelf(LOTRBlocks.CEDAR_LEAVES);
        dropSelf(LOTRBlocks.CHERRY_LEAVES);
        dropSelf(LOTRBlocks.CHESTNUT_LEAVES);
        dropSelf(LOTRBlocks.CYPRESS_LEAVES);
        dropSelf(LOTRBlocks.DARK_OAK_LEAVES);
        dropSelf(LOTRBlocks.DATE_PALM_LEAVES);
        dropSelf(LOTRBlocks.DRAGON_LEAVES);
        dropSelf(LOTRBlocks.FIR_LEAVES);
        dropSelf(LOTRBlocks.GREEN_OAK_LEAVES);
        dropSelf(LOTRBlocks.HOLLY_LEAVES);
        dropSelf(LOTRBlocks.JUNGLE_LEAVES);
        dropSelf(LOTRBlocks.KANUKA_LEAVES);
        dropSelf(LOTRBlocks.LAIRELOSSE_LEAVES);
        dropSelf(LOTRBlocks.LARCH_LEAVES);
        dropSelf(LOTRBlocks.LEBETHRON_LEAVES);
        dropSelf(LOTRBlocks.LEMON_LEAVES);
        dropSelf(LOTRBlocks.LIME_LEAVES);
        dropSelf(LOTRBlocks.MAHOGANY_LEAVES);
        dropSelf(LOTRBlocks.MALLORN_LEAVES);
        dropSelf(LOTRBlocks.MANGO_LEAVES);
        dropSelf(LOTRBlocks.MANGROVE_LEAVES);
        dropSelf(LOTRBlocks.MAPLE_LEAVES);
        dropSelf(LOTRBlocks.MIRK_OAK_LEAVES);
        dropSelf(LOTRBlocks.MIRK_OAK_RED_LEAVES);
        dropSelf(LOTRBlocks.OAK_LEAVES);
        dropSelf(LOTRBlocks.OLIVE_LEAVES);
        dropSelf(LOTRBlocks.ORANGE_LEAVES);
        dropSelf(LOTRBlocks.PALM_LEAVES);
        dropSelf(LOTRBlocks.PEAR_LEAVES);
        dropSelf(LOTRBlocks.PINE_LEAVES);
        dropSelf(LOTRBlocks.PLUM_LEAVES);
        dropSelf(LOTRBlocks.POMEGRANATE_LEAVES);
        dropSelf(LOTRBlocks.REDWOOD_LEAVES);
        dropSelf(LOTRBlocks.SHIRE_PINE_LEAVES);
        dropSelf(LOTRBlocks.SPRUCE_LEAVES);
        dropSelf(LOTRBlocks.WILLOW_LEAVES);
        dropSelf(LOTRBlocks.BLACK_STAINED_GLASS);
        dropSelf(LOTRBlocks.BLUE_STAINED_GLASS);
        dropSelf(LOTRBlocks.BROWN_STAINED_GLASS);
        dropSelf(LOTRBlocks.CYAN_STAINED_GLASS);
        dropSelf(LOTRBlocks.GRAY_STAINED_GLASS);
        dropSelf(LOTRBlocks.GREEN_STAINED_GLASS);
        dropSelf(LOTRBlocks.LIGHT_BLUE_STAINED_GLASS);
        dropSelf(LOTRBlocks.LIME_STAINED_GLASS);
        dropSelf(LOTRBlocks.MAGENTA_STAINED_GLASS);
        dropSelf(LOTRBlocks.ORANGE_STAINED_GLASS);
        dropSelf(LOTRBlocks.PINK_STAINED_GLASS);
        dropSelf(LOTRBlocks.PURPLE_STAINED_GLASS);
        dropSelf(LOTRBlocks.RED_STAINED_GLASS);
        dropSelf(LOTRBlocks.SILVER_STAINED_GLASS);
        dropSelf(LOTRBlocks.WHITE_STAINED_GLASS);
        dropSelf(LOTRBlocks.YELLOW_STAINED_GLASS);
        dropSelf(LOTRBlocks.GLASS);
        dropSelf(LOTRBlocks.ALMOND_SAPLING);
        dropSelf(LOTRBlocks.APPLE_SAPLING);
        dropSelf(LOTRBlocks.ASPEN_SAPLING);
        dropSelf(LOTRBlocks.BANANA_SAPLING);
        dropSelf(LOTRBlocks.BAOBAB_SAPLING);
        dropSelf(LOTRBlocks.BEECH_SAPLING);
        dropSelf(LOTRBlocks.CEDAR_SAPLING);
        dropSelf(LOTRBlocks.CHERRY_SAPLING);
        dropSelf(LOTRBlocks.CHESTNUT_SAPLING);
        dropSelf(LOTRBlocks.CYPRESS_SAPLING);
        dropSelf(LOTRBlocks.DATE_PALM_SAPLING);
        dropSelf(LOTRBlocks.DRAGON_SAPLING);
        dropSelf(LOTRBlocks.FIR_SAPLING);
        dropSelf(LOTRBlocks.GREEN_OAK_SAPLING);
        dropSelf(LOTRBlocks.HOLLY_SAPLING);
        dropSelf(LOTRBlocks.KANUKA_SAPLING);
        dropSelf(LOTRBlocks.LAIRELOSSE_SAPLING);
        dropSelf(LOTRBlocks.LARCH_SAPLING);
        dropSelf(LOTRBlocks.LEBETHRON_SAPLING);
        dropSelf(LOTRBlocks.LEMON_SAPLING);
        dropSelf(LOTRBlocks.LIME_SAPLING);
        dropSelf(LOTRBlocks.MAHOGANY_SAPLING);
        dropSelf(LOTRBlocks.MALLORN_SAPLING);
        dropSelf(LOTRBlocks.MANGO_SAPLING);
        dropSelf(LOTRBlocks.MANGROVE_SAPLING);
        dropSelf(LOTRBlocks.MAPLE_SAPLING);
        dropSelf(LOTRBlocks.MIRK_OAK_RED_SAPLING);
        dropSelf(LOTRBlocks.MIRK_OAK_SAPLING);
        dropSelf(LOTRBlocks.OLIVE_SAPLING);
        dropSelf(LOTRBlocks.ORANGE_SAPLING);
        dropSelf(LOTRBlocks.PALM_SAPLING);
        dropSelf(LOTRBlocks.PEAR_SAPLING);
        dropSelf(LOTRBlocks.PINE_SAPLING);
        dropSelf(LOTRBlocks.PLUM_SAPLING);
        dropSelf(LOTRBlocks.POMEGRANATE_SAPLING);
        dropSelf(LOTRBlocks.REDWOOD_SAPLING);
        dropSelf(LOTRBlocks.SHIRE_PINE_SAPLING);
        dropSelf(LOTRBlocks.WILLOW_SAPLING);
        dropSelf(LOTRBlocks.ACACIA_TRAPDOOR);
        dropSelf(LOTRBlocks.ALMOND_TRAPDOOR);
        dropSelf(LOTRBlocks.APPLE_TRAPDOOR);
        dropSelf(LOTRBlocks.ASPEN_TRAPDOOR);
        dropSelf(LOTRBlocks.BANANA_TRAPDOOR);
        dropSelf(LOTRBlocks.BAOBAB_TRAPDOOR);
        dropSelf(LOTRBlocks.BEECH_TRAPDOOR);
        dropSelf(LOTRBlocks.BIRCH_TRAPDOOR);
        dropSelf(LOTRBlocks.CEDAR_TRAPDOOR);
        dropSelf(LOTRBlocks.CHARRED_TRAPDOOR);
        dropSelf(LOTRBlocks.CHERRY_TRAPDOOR);
        dropSelf(LOTRBlocks.CHESTNUT_TRAPDOOR);
        dropSelf(LOTRBlocks.CYPRESS_TRAPDOOR);
        dropSelf(LOTRBlocks.DARK_OAK_TRAPDOOR);
        dropSelf(LOTRBlocks.DATE_PALM_TRAPDOOR);
        dropSelf(LOTRBlocks.DRAGON_TRAPDOOR);
        dropSelf(LOTRBlocks.FIR_TRAPDOOR);
        dropSelf(LOTRBlocks.GREEN_OAK_TRAPDOOR);
        dropSelf(LOTRBlocks.HOLLY_TRAPDOOR);
        dropSelf(LOTRBlocks.JUNGLE_TRAPDOOR);
        dropSelf(LOTRBlocks.KANUKA_TRAPDOOR);
        dropSelf(LOTRBlocks.LAIRELOSSE_TRAPDOOR);
        dropSelf(LOTRBlocks.LARCH_TRAPDOOR);
        dropSelf(LOTRBlocks.LEBETHRON_TRAPDOOR);
        dropSelf(LOTRBlocks.LEMON_TRAPDOOR);
        dropSelf(LOTRBlocks.LIME_TRAPDOOR);
        dropSelf(LOTRBlocks.MAHOGANY_TRAPDOOR);
        dropSelf(LOTRBlocks.MALLORN_TRAPDOOR);
        dropSelf(LOTRBlocks.MANGO_TRAPDOOR);
        dropSelf(LOTRBlocks.MANGROVE_TRAPDOOR);
        dropSelf(LOTRBlocks.MAPLE_TRAPDOOR);
        dropSelf(LOTRBlocks.MIRK_OAK_TRAPDOOR);
        dropSelf(LOTRBlocks.OLIVE_TRAPDOOR);
        dropSelf(LOTRBlocks.ORANGE_TRAPDOOR);
        dropSelf(LOTRBlocks.PALM_TRAPDOOR);
        dropSelf(LOTRBlocks.PEAR_TRAPDOOR);
        dropSelf(LOTRBlocks.PINE_TRAPDOOR);
        dropSelf(LOTRBlocks.PLUM_TRAPDOOR);
        dropSelf(LOTRBlocks.POMEGRANATE_TRAPDOOR);
        dropSelf(LOTRBlocks.REDWOOD_TRAPDOOR);
        dropSelf(LOTRBlocks.ROTTEN_TRAPDOOR);
        dropSelf(LOTRBlocks.SHIRE_PINE_TRAPDOOR);
        dropSelf(LOTRBlocks.SPRUCE_TRAPDOOR);
        dropSelf(LOTRBlocks.WILLOW_TRAPDOOR);
        dropSelf(LOTRBlocks.BLUE_DWARF_BARS);
        dropSelf(LOTRBlocks.BRONZE_BARS);
        dropSelf(LOTRBlocks.DWARF_BARS);
        dropSelf(LOTRBlocks.GALADHRIM_BARS);
        dropSelf(LOTRBlocks.GALADHRIM_WOOD_BARS);
        dropSelf(LOTRBlocks.GOLD_BARS);
        dropSelf(LOTRBlocks.HIGH_ELF_BARS);
        dropSelf(LOTRBlocks.HIGH_ELF_WOOD_BARS);
        dropSelf(LOTRBlocks.MITHRIL_BARS);
        dropSelf(LOTRBlocks.ORC_STEEL_BARS);
        dropSelf(LOTRBlocks.REED_BARS);
        dropSelf(LOTRBlocks.SILVER_BARS);
        dropSelf(LOTRBlocks.URUK_BARS);
        dropSelf(LOTRBlocks.WOOD_ELF_BARS);
        dropSelf(LOTRBlocks.WOOD_ELF_WOOD_BARS);

        dropSelf(LOTRBlocks.BLUE_DWARVEN_CHANDELIER);
        dropSelf(LOTRBlocks.BRONZE_CHANDELIER);
        dropSelf(LOTRBlocks.DWARVEN_CHANDELIER);
        dropSelf(LOTRBlocks.GOLD_CHANDELIER);
        dropSelf(LOTRBlocks.HIGH_ELVEN_CHANDELIER);
        dropSelf(LOTRBlocks.IRON_CHANDELIER);
        dropSelf(LOTRBlocks.MALLORN_BLUE_CHANDELIER);
        dropSelf(LOTRBlocks.MALLORN_GOLD_CHANDELIER);
        dropSelf(LOTRBlocks.MALLORN_GREEN_CHANDELIER);
        dropSelf(LOTRBlocks.MALLORN_SILVER_CHANDELIER);
        dropSelf(LOTRBlocks.MITHRIL_CHANDELIER);
        dropSelf(LOTRBlocks.MORGUL_CHANDELIER);
        dropSelf(LOTRBlocks.ORC_CHANDELIER);
        dropSelf(LOTRBlocks.SILVER_CHANDELIER);
        dropSelf(LOTRBlocks.URUK_CHANDELIER);
        dropSelf(LOTRBlocks.WOOD_ELVEN_CHANDELIER);

        // Doors: only drop one item per two-block door
        add(LOTRBlocks.ACACIA_DOOR, this::createDoorTable);
        add(LOTRBlocks.ALMOND_DOOR, this::createDoorTable);
        add(LOTRBlocks.APPLE_DOOR, this::createDoorTable);
        add(LOTRBlocks.ASPEN_DOOR, this::createDoorTable);
        add(LOTRBlocks.BANANA_DOOR, this::createDoorTable);
        add(LOTRBlocks.BAOBAB_DOOR, this::createDoorTable);
        add(LOTRBlocks.BEECH_DOOR, this::createDoorTable);
        add(LOTRBlocks.BIRCH_DOOR, this::createDoorTable);
        add(LOTRBlocks.CEDAR_DOOR, this::createDoorTable);
        add(LOTRBlocks.CHARRED_DOOR, this::createDoorTable);
        add(LOTRBlocks.CHERRY_DOOR, this::createDoorTable);
        add(LOTRBlocks.CHESTNUT_DOOR, this::createDoorTable);
        add(LOTRBlocks.CYPRESS_DOOR, this::createDoorTable);
        add(LOTRBlocks.DARK_OAK_DOOR, this::createDoorTable);
        add(LOTRBlocks.DATE_PALM_DOOR, this::createDoorTable);
        add(LOTRBlocks.DRAGON_DOOR, this::createDoorTable);
        add(LOTRBlocks.FIR_DOOR, this::createDoorTable);
        add(LOTRBlocks.GREEN_OAK_DOOR, this::createDoorTable);
        add(LOTRBlocks.HOLLY_DOOR, this::createDoorTable);
        add(LOTRBlocks.JUNGLE_DOOR, this::createDoorTable);
        add(LOTRBlocks.KANUKA_DOOR, this::createDoorTable);
        add(LOTRBlocks.LAIRELOSSE_DOOR, this::createDoorTable);
        add(LOTRBlocks.LARCH_DOOR, this::createDoorTable);
        add(LOTRBlocks.LEBETHRON_DOOR, this::createDoorTable);
        add(LOTRBlocks.LEMON_DOOR, this::createDoorTable);
        add(LOTRBlocks.LIME_DOOR, this::createDoorTable);
        add(LOTRBlocks.MAHOGANY_DOOR, this::createDoorTable);
        add(LOTRBlocks.MALLORN_DOOR, this::createDoorTable);
        add(LOTRBlocks.MANGO_DOOR, this::createDoorTable);
        add(LOTRBlocks.MANGROVE_DOOR, this::createDoorTable);
        add(LOTRBlocks.MAPLE_DOOR, this::createDoorTable);
        add(LOTRBlocks.MIRK_OAK_DOOR, this::createDoorTable);
        add(LOTRBlocks.OLIVE_DOOR, this::createDoorTable);
        add(LOTRBlocks.ORANGE_DOOR, this::createDoorTable);
        add(LOTRBlocks.PALM_DOOR, this::createDoorTable);
        add(LOTRBlocks.PEAR_DOOR, this::createDoorTable);
        add(LOTRBlocks.PINE_DOOR, this::createDoorTable);
        add(LOTRBlocks.PLUM_DOOR, this::createDoorTable);
        add(LOTRBlocks.POMEGRANATE_DOOR, this::createDoorTable);
        add(LOTRBlocks.REDWOOD_DOOR, this::createDoorTable);
        add(LOTRBlocks.ROTTEN_DOOR, this::createDoorTable);
        add(LOTRBlocks.SHIRE_PINE_DOOR, this::createDoorTable);
        add(LOTRBlocks.SPRUCE_DOOR, this::createDoorTable);
        add(LOTRBlocks.WILLOW_DOOR, this::createDoorTable);
    }
}