"""Regenerates the unsmeltery's item model and its texture.

    python3 tools/gen_unsmeltery_item_model.py     (from the repo root)

Same approach as tools/gen_totem_item_models.py, and for the same reason: the
block is RenderShape.INVISIBLE and drawn by LOTRUnsmelteryRenderer, so the ITEM
needs an ordinary block model. Boxes come from LOTRModelUnsmeltery, put through
the renderer's translate(0.5,1.5,0.5) + scale(1,-1,-1), then a further 180 about
Y so the cauldron's front faces the north face a block item icon shows.

The two iron pivot panels at the tops of the stands ARE included. They sit on a
child part tilted 45 degrees about X; a JSON element expresses that with its own
"rotation", and 45 is one of the permitted angles. Note the sign: conjugating
Rx(45) by the composed diag(-1,-1,1) gives Rx(-45), so the element angle is -45.

Keep the box list in sync with LOTRUnsmelteryModel.createLayer().
"""
import json, collections
from PIL import Image

SHEET_SRC = 'src/main/resources/assets/lotr/textures/entity/unsmeltery_idle.png'
SHEET_DST = 'src/main/resources/assets/lotr/textures/block/unsmeltery_sheet.png'
MODEL     = 'src/main/resources/assets/lotr/models/block/unsmeltery_inventory.json'

# name, texOffs, (w,h,d), rotationPoint, boxFrom, mirrored
BOXES = [
  ("base",     (0,0),  (14,3,14),  (0,21,0),  (-7,0,-7),   False),
  ("body",     (0,17), (14,10,14), (0,12,0),  (-7,-2,-7),  False),
  ("rim_n",    (0,41), (14,2,1),   (0,12,0),  (-7,-4,-7),  False),
  ("rim_s",    (0,41), (14,2,1),   (0,12,0),  (-7,-4,6),   False),
  ("rim_w",    (0,44), (1,2,12),   (0,12,0),  (-7,-4,-6),  False),
  ("rim_e",    (0,44), (1,2,12),   (0,12,0),  (6,-4,-6),   False),
  ("stand_r",  (56,6), (1,12,2),   (-7,23,0), (-0.9,-12,-1), False),
  ("stand_l",  (56,6), (1,12,2),   (7,23,0),  (-0.1,-12,-1), True),
  # The pivot panels. Their rotation point is the stand's, plus the child
  # offset (0,-11,0); the box is given relative to that point.
  ("pivot_r",  (56,0), (1,3,3),    (-7,12,0), (-1,-2,-1),  False),
  ("pivot_l",  (56,0), (1,3,3),    (7,12,0),  (0,-2,-1),   True),
]

# Element rotations, keyed by box name: the 45 degree tilt on the pivot panels.
# Rotation origin is the child part's own rotation point, in block space.
ROTATIONS = {
  "pivot_r": ((-7, 12, 0), -45.0),
  "pivot_l": ((7, 12, 0), -45.0),
}

def entity_rects(off, size):
    u, v = off
    w, h, d = size
    return {
      "down":  (u+d,       v,   u+d+w,     v+d),      # minY
      "up":    (u+d+w,     v,   u+d+2*w,   v+d),      # maxY
      "west":  (u,         v+d, u+d,       v+d+h),    # minX
      "north": (u+d,       v+d, u+d+w,     v+d+h),    # minZ
      "east":  (u+d+w,     v+d, u+2*d+w,   v+d+h),    # maxX
      "south": (u+2*d+w,   v+d, u+2*d+2*w, v+d+h),    # maxZ
    }

# Composed rotation x -> -x, y -> -y, z -> +z.
FACE_SOURCE = {"up":"down", "down":"up", "north":"north", "south":"south",
               "east":"west", "west":"east"}
MIRRORED = {"east":"west", "west":"east"}

def to_block(rp, off, size):
    lo = [rp[i] + off[i] for i in range(3)]
    hi = [lo[0]+size[0], lo[1]+size[1], lo[2]+size[2]]
    xs = sorted((8 - lo[0], 8 - hi[0]))
    ys = sorted((24 - lo[1], 24 - hi[1]))
    zs = sorted((8 + lo[2], 8 + hi[2]))
    r = lambda v: round(v, 4)          # the model uses 0.9/0.1 offsets
    return [r(xs[0]), r(ys[0]), r(zs[0])], [r(xs[1]), r(ys[1]), r(zs[1])]

src = Image.open(SHEET_SRC).convert('RGBA')
assert src.size == (64, 64), src.size
src.save(SHEET_DST)          # already square; copied so it lands on the block atlas
SCALE = 16.0 / 64.0

elements = []
for name, off, size, rp, boxfrom, mirror in BOXES:
    a, b = to_block(rp, boxfrom, size)
    for v in a + b:
        assert -0.001 <= v <= 16.001, (name, a, b)
    rects = entity_rects(off, size)
    faces = collections.OrderedDict()
    for face in ("down", "up", "north", "south", "west", "east"):
        srcf = FACE_SOURCE[face]
        if mirror:
            srcf = MIRRORED.get(srcf, srcf)
        x0, y0, x1, y1 = rects[srcf]
        faces[face] = {"uv": [round(x0*SCALE,3), round(y0*SCALE,3),
                              round(x1*SCALE,3), round(y1*SCALE,3)],
                       "texture": "#sheet"}
    element = collections.OrderedDict(
        [("__comment", name), ("from", a), ("to", b)])
    if name in ROTATIONS:
        (ox, oy, oz), angle = ROTATIONS[name]
        element["rotation"] = {
            "origin": [round(8 - ox, 4), round(24 - oy, 4), round(8 + oz, 4)],
            "axis": "x",
            "angle": angle,
        }
    element["faces"] = faces
    elements.append(element)

model = collections.OrderedDict([
    ("__comment", "GENERATED by tools/gen_unsmeltery_item_model.py -- do not "
                  "hand-edit. Item form only; the world model is "
                  "LOTRUnsmelteryRenderer."),
    ("parent", "minecraft:block/block"),
    ("textures", {"sheet": "lotr:block/unsmeltery_sheet",
                  "particle": "lotr:block/unsmeltery_sheet"}),
    ("elements", elements),
])
json.dump(model, open(MODEL, "w"), indent=2)
open(MODEL, "a").write("\n")
print(f"{len(elements)} elements, {len(elements)*6} textured faces")
for e in elements:
    print("  ", e["__comment"], e["from"], "->", e["to"])
